celeritas-project/celeritas

src/random/GenerateCanonical.i.hh
src/random/RngEngine.cuh
src/random/RngStateStore.cu
src/random/RngStateStore.hh

A few minor tweaks to the RNG based on some of the other recent code changes:
- Use `operator=` for initialization
- Use friend class for GenerateCanonical specialization, it seems more appropriate
- Use custom deleter for `unique_ptr` to eliminate need for explicitly defaulting destructor/move

Tweak RNG engine interface

---

.gitmodules
CMakeLists.txt
app/CMakeLists.txt
app/demo-interactor/KNDemoIO.cc
app/demo-interactor/KNDemoIO.hh
app/demo-interactor/KNDemoKernel.cu
app/demo-interactor/KNDemoKernel.hh
app/demo-interactor/KNDemoRunner.cc
app/demo-interactor/KNDemoRunner.hh
app/demo-interactor/demo-interactor.cc
app/demo-interactor/simple-driver.py
cmake/CeleritasLoadSubmodule.cmake
external/CMakeLists.txt
external/cmake/nlohmann_json.cmake
scripts/dev/celeritas-gen.py
src/CMakeLists.txt
src/physics/base/ParticleTrackView.hh
src/physics/base/ParticleTrackView.i.hh
src/physics/base/SecondaryAllocatorStore.hh
src/physics/em/KleinNishinaInteractorPointers.hh
src/random/cuda/RngStatePointers.hh
src/random/cuda/RngStateStore.cc

This is a simple demonstration app for physics.
- Only gamma transport with Klein-Nishina model for Compton scattering
- Instantly kills secondary electrons, and lower energy cutoff of model (10 keV) is used as cutoff for gammas
- Infinite medium with no internal simulation time; no XS calculation or step length sampling
- Basic problem input parameter is incident energy and solver parameters
- Outputs timing diagnostics, accumulated energy deposition per step, total number of living tracks
A future PR will extend this to using cross section calculation (sampling the interaction length) and tallying (accumulating Z-dependent energy deposition), allowing the first apples-to-apples performance and modeling comparison to Geant4.
Until then, this simple demo serves as a tool for rapidly …

Klein-Nishina demo app

---

src/random/cuda/RngEngine.cuh
src/random/cuda/RngEngine.i.cuh
src/random/cuda/RngStatePointers.hh
test/random/cuda/RngEngine.test.cu

Make RngEngine work on both host and device.  This PR addresses and replaces the issue #19.
After merged, need to add options to use other generators/random states such as 
MRG32k3a/curandStateMRG32k3a_t, Random123/curandStatePhilox4_32_10_t and etc, which
should work out of box.  Also, generalize RngEngine.test.cu which currently works only for curandStateXORWOW.

Add host/device compatible RNG

---

CMakeLists.txt

CMake 3.18 introduced policy [`CMP0104`](https://cmake.org/cmake/help/v3.18/policy/CMP0104.html) on the initialization of the new [`CMAKE_CUDA_ARCHITECTURES`](https://cmake.org/cmake/help/v3.18/variable/CMAKE_CUDA_ARCHITECTURES.html#variable:CMAKE_CUDA_ARCHITECTURES) variable and subsequent use of code generation flags. Without this policy being set to `NEW`, warnings are emitted at CMake generation time about `CUDA_ARCHITECTURES` not being set for targets.
Bump max CMake policy range to 3.18 to set a default for `CMAKE_CUDA_ARCHITECTURES` if not supplied by the user.
This can still result in `nvlink` errors when linking `vecgeom_static` if that was compiled with architectures incompatible(?) with that for Celeritas. Not sure how to check that yet.

Increase max policy range for CMake to 3.18

---

CMakeLists.txt
app/CMakeLists.txt
app/demo-interactor/HostDetectorStore.cc
app/demo-interactor/HostDetectorStore.hh
app/demo-interactor/HostKNDemoRunner.cc
app/demo-interactor/HostKNDemoRunner.hh
app/demo-interactor/HostStackAllocatorStore.hh
app/demo-interactor/PhysicsArrayParams.cc
app/demo-interactor/PhysicsArrayParams.hh
app/demo-interactor/detail/DetectorUtils.cu
app/demo-interactor/host-demo-interactor.cc
scripts/build/wildstyle.cmake

This adds a CPU version of the Klein Nishina application.  The same driver will work for both applications.  `CELERITAS_USE_CUDA` must still be enabled to use the app because it will do some spurious copies to the device during the cross section setup (this does not get factored into runtime comparisons).
The same driver code works for both applications except of course that the `grid_params` gets ignored.  To see an example and runtime comparisons between the CPU and GPU code see https://github.com/celeritas-project/benchmarks/blob/master/klein-nishina/celeritas-results-cpu/analysis.ipynb.
This app does a traditional loop-based (history) approach for the tracks.  It does not implement the same event loop algorithm as in the GPU case.  Generally, the history approach is more efficient on …

Klein-Nishina CPU performance application

---

src/base/Range.hh
test/CMakeLists.txt
test/base/Range.test.cc
test/base/Range.test.cu
test/base/Range.test.hh

To help device/kernel function authors write cleaner loops, qualify Range types and functions for host and device. The Range test is extended to provide an optional CUDA component when this is available, but is only stubbed in. It can be implemented once checks of PTX confirm any cost to implementing loops this way on the device.
As discussed on Slack, checks need to be done first to confirm the code is optimised well on the device side. If a basic test is needed to do that, let me know!

Qualify Range types and functions for host and device

---

test/CMakeLists.txt

`ElementSelector` was set in CMake as a Cuda test instead of a host-side test.

Fix designation of ElementSelector test as a host test

---

src/base/Algorithms.hh
test/CMakeLists.txt
test/base/Algorithms.test.cc

`std::pow(a, 3)` takes some 245 operations. A templated function `cube(const T& a)` is added in this commit that instead uses `a * a * a` which takes only 9 operations.

Add templated cube() to Algorithms.h

---

app/geant-exporter/GeantPhysicsTableWriterHelper.hh
app/geant-exporter/geant-exporter.cc
src/base/Assert.hh
src/base/DeviceAllocation.nocuda.cc
src/base/Macros.hh
src/base/Memory.nocuda.cc
src/geometry/detail/VGNavStateStore.nocuda.cc

I discovered that celeritas generates warnings when Geant4 is enabled in opt mode, due to the "Check(0)" I asked @stognini to put in since I hadn't added a "not reachable" macro. With the addition of this macro, not-reachable shows the expected failure modes and builds correctly.

Add "not reachable" macros

---

app/demo-interactor/demo-interactor.cc
app/demo-interactor/host-demo-interactor.cc
scripts/dev/celeritas-gen-hackathon.py
src/base/Quantity.hh
src/physics/base/Interaction.hh
src/physics/em/EPlusGGInteractor.hh
src/physics/em/EPlusGGInteractor.i.hh
test/CMakeLists.txt
test/base/Quantity.test.cc
test/physics/InteractorHostTestBase.cc
test/physics/base/Particle.test.cc
test/physics/em/BetheBlochInteractor.test.cc
test/physics/em/BremRelInteractor.test.cc
test/physics/em/EPlusGGInteractor.test.cc
test/physics/em/KleinNishinaInteractor.test.cc
test/physics/em/LivermoreInteractor.test.cc
test/physics/em/MollerBhabhaInteractor.test.cc
test/physics/em/RayleighInteractor.test.cc
test/physics/em/UrbanInteractor.test.cc
test/physics/em/WentzelInteractor.test.cc

While doing some preparatory work for the multiple models/processes, I noticed the EPlusGG test wasn't enabled, and the "at rest" portion wasn't being tested.
- Added an "infinite" quantity so that models with no upper energy bound don't have to choose an arbitrary number
- Replaced hard-coded double-precision math with `real_type` and implicit conversions in case we ever want to experiment with single-precision
- Delayed evaluation of expressions until they're used, reducing register pressure
See https://github.com/celeritas-project/cuda-test-snippets/commit/109392ddb7c247b55e6942b7c0a82f7efbfc1b92 for the changes in register usage/spill due to the minor tweaks.

Extend non-numeric quantity, enable tests and tweak annihilation process

---

app/demo-interactor/demo-interactor.cc
app/demo-interactor/host-demo-interactor.cc
app/demo-rasterizer/RDemoRunner.cc
app/demo-rasterizer/demo-rasterizer.cc
app/geant-exporter/geant-exporter.cc
src/CMakeLists.txt
src/base/Assert.hh
src/base/ColorUtils.cc
src/comm/Communicator.hh
src/comm/Communicator.mpi.cc
src/comm/Communicator.nompi.cc
src/comm/Logger.cc
src/comm/Logger.hh
src/comm/LoggerTypes.cc
src/comm/LoggerTypes.hh
src/comm/MpiTypes.hh
src/comm/detail/LoggerMessage.cc
src/comm/detail/LoggerMessage.hh
src/geometry/GeoParams.cc
test/CMakeLists.txt
test/comm/Communicator.test.cc
test/comm/Logger.test.cc
test/gtest/detail/ParallelHandler.cc

Add a low-overhead, parallel-enabled, extensible logger utility that looks like `cout` but is more clever.
The logger here is based off the logger in Shift (which is inspired in terminology by the python logging utilities).
- There are two global loggers: one standard logger (where all processes are presumed to be running the same code segment), and a "local" logger which is for a condition that's expected to vary between processes.
- If the runtime requested logging level is above the log statement, the `operator<<` is not evaluated for the object being streamed. (The same is true for the cases for the standard logger on all non-master processes.)
- The logging handler and log levels can be changed arbitrarily. The log handler is just a simple functor that takes the source file/line, the …

Add logger

---

src/CMakeLists.txt
src/physics/material/MaterialParams.cc
src/physics/material/MaterialParamsPointers.hh
src/physics/material/MaterialStatePointers.hh
src/physics/material/MaterialStateStore.cc
src/physics/material/MaterialStateStore.hh
src/physics/material/MaterialTrackView.hh
src/physics/material/MaterialTrackView.i.hh
test/physics/InteractorHostTestBase.cc
test/physics/InteractorHostTestBase.hh
test/physics/em/BremRelInteractor.test.cc
test/physics/material/Material.test.cc
test/physics/material/Material.test.cu

- Add material params and material track view to the interactor test (will be needed for models that sample cross sections and use other material properties)
- Add device scratch space for cross section storage (or anything else that scales with the number of elements in a material)

Add element scratch space and add to interactor test

---

.jenkins
scripts/build/docker.sh
scripts/docker/Dockerfile
scripts/docker/README.md
scripts/docker/ci/Dockerfile
scripts/docker/ci/entrypoint.bash
scripts/docker/env.yaml
test/gtest/detail/TestMain.cc

This defines a dockerfile with the full Celeritas toolchain on Ubuntu 20 with CUDA 11.1 and Spack 0.16 for CUDA sm_70 capabilities. The CI integration clones the image and builds with the included script, posting the results to a [Celeritas Jenkins status page](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Celeritas/activity/) and marking the PR as passing/failing.

Add Dockerfile and enable Jenkins CI

---

src/base/Algorithms.hh
src/physics/base/ParticleMd.hh
src/physics/material/ElementDef.hh
src/physics/material/ElementView.hh
src/physics/material/ElementView.i.hh
src/physics/material/MaterialParams.cc
src/physics/material/detail/Utils.cc
src/physics/material/detail/Utils.hh
test/base/Algorithms.test.cc
test/physics/material/Material.test.cc

The coulomb correction factor in the review of particle physics (and implemented in geant in multiple places) uses a couple of magic numbers which are actually values from an infinite series expansion as derived in https://arxiv.org/abs/1204.3675v3 . This MR adds the Coulomb correction factor to the element definition data and the ElementView, and then (in a separate commit) implements a more accurate form calculated in [this python script](https://github.com/celeritas-project/celeritas-docs/blob/master/notes/coulomb-correction/eval.py).

Add Coulomb correction to element view and increase accuracy

---

src/base/Quantity.hh
src/base/detail/InitializedValue.hh
src/geometry/GeoParams.cc
test/base/DeviceAllocation.test.cc
test/base/Quantity.test.cc
test/geometry/GeoParams.test.cc
test/gtest/detail/Macros.hh

- Use  `std::exchange` in `InitializedValue` and make its arguments move-friendly
- Add `swap` for `Quantity` needed for #72 
- Improve failure mode for GeoParams when CUDA is disabled
- Add `SKIP` macro to test macros

Improve InitializedValue and Quantity

---

test/physics/InteractorHostTestBase.hh
test/physics/em/EPlusGGInteractor.test.cc
test/physics/em/KleinNishinaInteractor.test.cc
test/random/DiagnosticRngEngine.hh
test/random/distributions/ExponentialDistribution.test.cc
test/random/distributions/IsotropicDistribution.test.cc

This adds a thin wrapper to the testing infrastructure so that our physics (and RNG) tests can query how many times the RNG sampler is called, which is a useful noninvasive diagnostic tool for understanding rejection rates in some of our physics samplers.

Add diagnostic RNG engine to test sampling efficiency

---

src/base/Assert.cc
src/base/Assert.hh
src/comm/Logger.hh
src/comm/LoggerTypes.hh
src/sim/TrackInitializerStore.cc

Add an
```c++
INSIST(condition, "description " << with_streamable << " user-facing error message");
```
macro for runtime conditions that should always be enabled (because they depend on the runtime environment and not on the correctness of the code).

Add always-on INSIST macro

---

src/physics/base/Interaction.hh
src/physics/em/PhotoelectricInteractor.i.hh
test/physics/InteractorHostTestBase.cc
test/physics/em/PhotoelectricInteractor.test.cc

Small addition based on our discussion at today’s physics meeting and on #89: this lets us to keep track of local energy deposition in an interaction.

Store local energy deposition

---

app/demo-interactor/KNDemoKernel.cu
app/demo-interactor/detail/DetectorUtils.cu
app/demo-rasterizer/RDemoKernel.cu
src/base/Memory.cu
src/geometry/detail/VGNavStateStore.cuda.cc
src/random/cuda/detail/RngStateInit.cu
src/sim/StatePointers.hh
src/sim/detail/InitializeTracks.cu
src/sim/detail/SimStateInit.cu

- Move anonymous namespace inside celeritas namespace
- Suffix with `kernel` instead of `impl` or nothing
- Change "device synchronize" to "peek error"

Unify kernel namespaces and error checking

---

scripts/dev/install-spack.sh
src/physics/em/BetheHeitlerInteractor.i.hh

Based on the discussion on slack, the probability for selecting the f1/g1 and f2/g2 functions in the BetheHeitlerInteractor is not correct. This PR uses the two-argument form of `BernoulliDistribution` with the values N1 and N2 from the Geant4 physics reference manual (so that the probability of selecting f1/g1 is N1/(N1 + N2)). I also put in a small fix in install-spack.sh.

Fix for energy sampling in BetheHeithlerInteractor

---

app/CMakeLists.txt
app/geant-exporter/GeantPhysicsTableWriter.cc
app/geant-exporter/geant-exporter.cc
doc/CMakeLists.txt
scripts/build/docker.sh
scripts/docker/ci/launch-testing.sh
src/CMakeLists.txt
src/base/Assert.cc
src/base/Assert.hh
src/base/DeviceAllocation.nocuda.cc
src/comm/Communicator.nompi.cc
src/geometry/detail/VGNavStateStore.nocuda.cc
src/io/EventReader.cc
src/io/EventReader.hh
src/io/EventReader.nohepmc.cc
src/io/RootImporter.cc
src/io/RootImporter.hh
src/io/RootImporter.noroot.cc
test/CMakeLists.txt

I'm adding SWIG wrappers to celeritas (primarily for my own personal debugging/data exploration, could be useful elsewhere though), and it's better to not have to conditionally wrap files and objects based on what's configured. With this change, all the classes are defined and their headers can be included (aside from vecgeom, which we can't forward declare due to  inline namespaces and macros). Tests that rely on disabled configuration issues now build but are "disabled" when running through cmake, and invoking them manually explains why they're disabled:
```
../src/io/RootImporter.noroot.cc:21:
celeritas: required dependency is disabled in this build: ROOT
```

Improve ROOT compatibility and ability to build without TPLs

---

CMakeLists.txt
src/CMakeLists.txt

HepMC3's cmake config file does not provide imported targets for its libraries. This caused build errors between spack view and module builds. Celeritas does not add the include directory for HepMC3 directly, resulting in view-based builds finding HepMC3 headers incidently due to the view holding all used packages. Module based builds exposed this issue due to the separate include directories for each module.
When using HepMC3, create a "HepMC3::HepMC3" imported target if one does not exist, allowing for future supply of the target by HepMC3 itself (I'll put a MR request in upstream when I get a chance). Use this target to link in place of the "HEPMC3_LIB" variable to propagate the include path.
NB: I've only tested this in a spack-view setup, but the basic linking and path propagation is …

Provide an imported target for HepMC3

---

src/CMakeLists.txt
src/physics/em/EPlusGGModel.cc
src/physics/em/detail/EPlusGG.cu
src/physics/em/detail/EPlusGG.hh

This add a kernel for the EPlusGG interactor and adds the kernel call to the `EPlusGGModel::interact()` function call.

Add EPlusGG interactor kernel

---

src/CMakeLists.txt
src/io/RootInterfaceLinkDef.h

With these change one can do (with the script below):
```
LD_LIBRARY_PATH=${PWD}/src:${LD_LIBRARY_PATH} CELER_DISABLE_PARALLEL=true python celeritas/example.py
status: Opening ROOT file
status: Loading particle data
/wclustre/g4p/pcanal/geant/sources/celeritas/src/comm/Device.cuda.cc:35: warning: Disabling GPU support since no CUDA devices are present
status: Loading physics processes
status: Loading geometry data
status: Loading material data
['annihilation', 'conversion', 'rayleigh', 'e_ioni', 'compton', 'e_brem', 'coulomb_scat', 'photoelectric', 'msc']
['lambda_prim']
```
and in C++
```
LD_LIBRARY_PATH=${PWD}/src:${LD_LIBRARY_PATH} CELER_DISABLE_PARALLEL=true root.exe -b -l celeritas/example.C -q
Processing celeritas/example.C...
status: Opening ROOT file
status: Loading particle data …
```

Fix ROOT autoloading and add RootImporter to the dict.

---

scripts/dev/celeritas-gen.py
scripts/dev/rename-macros.py

I was lazy when I created the `celeritas-gen.py` and hardcoded the year to 2020, so even now new files have been showing up with that year (oops). This updates the script to use the actual current year. I don't plan on any global find-replaces for copyright year.

Update copyright year in stub file generator

---

src/base/Assert.cc
src/base/Assert.hh
src/physics/em/BetheBlochInteractor.i.hh
src/physics/em/BremRelInteractor.i.hh
src/physics/em/MollerBhabhaInteractor.i.hh
src/physics/em/RayleighInteractor.i.hh
src/physics/em/UrbanInteractor.i.hh
src/physics/em/WentzelInteractor.i.hh
src/physics/grid/ValueGridBuilder.cc

Another bit of granularity for assertion messages. This will make it easier to grep the code for missing features rather than for code paths that are expected to be unreachable.

Add "not implemented" assertion macro

---

scripts/build/emmet.cmake
src/physics/base/Secondary.hh
src/physics/em/detail/BetheHeitler.cu
src/physics/em/detail/KleinNishina.cu
src/physics/em/detail/LivermorePE.cu

@amandalund @pcanal
---
On emmet we saw the following error (which didn't appear on the CI, which runs CUDA 11.1):
```
nvlink error   : Size doesn't match for '_ZN9celeritas9SecondaryC1Ev$53' in 'CMakeFiles/celeritas.dir/physics/em/detail/EPlusGG.cu.o', first specified in 'CMakeFiles/celeritas.dir/physics/em/detail/BetheHeitler.cu.o'
nvlink fatal   : merge_elf failed
```
A bug report for LLVM hinted at a bug in `nvlink` regarding weak symbols: https://bugs.llvm.org/show_bug.cgi?id=40893 . Using the nvcc `-keep` flag led to finding the Secondary's constructor was defined as a weak symbol, and internally it stores two values (for the initialization values of def_id and energy), which are defined internally in BetheHeitler as
```
.weak .global .align 4 .b8 _ZN9celeritas9SecondaryC1Ev$53[4] = …
```

Workaround nvlink bug

---

test/sim/TrackInitializerStore.test.cc

Running on a local system with gcc9, CUDA 11 and a Quadro P400, I found a couple of failures in the `sim/TrackInitializerStore` test, the sections failing being:
```
52: [ RUN      ] TrackInitTest.run
52: info: Loading from GDML at <path>/celeritas.git/test/geometry/data/twoBoxes.gdml
52: status: Initializing tracking information
52: status: Converting to CUDA geometry
52: status: Transferring geometry to GPU
52: <path>/celeritas.git/test/sim/TrackInitializerStore.test.cc:163: Failure
52: Values in: output.initializer_id
52:  Expected: expected.initializer_id
52: 2 of 5 elements differ
52: i         EXPECTED           ACTUAL
52: 3               16u               17u
52: 4               17u               16u
52: 
52: <path>/celeritas.git/test/sim/TrackInitializerStore.test.cc:171: Failure …
```

Allow for non-deterministic IDs in TrackInitializerStore test

---

CMakeLists.txt

- Fail when `VECGEOM_CUDA_ARCHITECTURES` is specified on older versions of CMake (see #123 )
- Update external googletest submodule to eliminate warning under CMake 3.19 (@mrguilima )

Build system improvements

---

src/CMakeLists.txt
src/base/DeviceVector.hh
src/base/DeviceVector.i.hh
src/base/VectorUtils.hh
src/base/VectorUtils.i.hh
src/physics/base/PhysicsParams.cc
src/physics/em/LivermorePEParams.cc
src/physics/em/MockXsCalculator.hh
src/physics/grid/PhysicsGridCalculator.hh
src/physics/grid/PhysicsGridCalculator.i.hh
src/physics/grid/ValueGridBuilder.cc
src/physics/grid/ValueGridBuilder.hh
src/physics/grid/ValueGridStore.cc
src/physics/grid/ValueGridStore.hh
src/physics/grid/XsGridInterface.hh
test/CMakeLists.txt
test/base/VectorUtils.test.cc
test/physics/grid/ValueGridBuilder.test.cc
test/physics/grid/ValueGridStore.test.cc

Add support code to construct lots of cross section grids. I implemented the grid construction needed for cross section, slowing down, and range tables; but not the generic ones by the livermore cross section lookups.

Add value grid construction and storage

---

src/base/ArrayUtils.i.hh
src/base/Atomics.hh
src/base/Memory.cu
src/base/TypeDemangler.cc
src/comm/detail/LoggerMessage.cc
src/physics/grid/ValueGridBuilder.cc
src/physics/grid/ValueGridBuilder.hh
src/physics/grid/XsGridInterface.hh

Add `CELER_EXPECT(ptr)` for the pass-by-reference cases.

Add expectations for pass-by-pointer mutable references

---

src/geometry/LinearPropagator.hh
src/geometry/LinearPropagator.i.hh
src/sim/TrackInitializerStore.cc
src/sim/TrackInitializerStore.hh
test/geometry/LinearPropagator.test.cc
test/geometry/LinearPropagator.test.cu
test/sim/TrackInitializerStore.test.cc

In addition we have 4 categories of exceptions:
* `to/from_json` where the signature is imposed by the `nlohmann` library
* `swap` to match the usual signature from the C++ standard.
* Passing random number generator and engine  to match the usual signature from the C++ standard?
and the potentially updatable:
* make_span ... maybe because taking the address of an array is not easy
```
app/demo-interactor/KNDemoIO.hh:void to_json(nlohmann::json& j, const CudaGridParams& value);
app/demo-interactor/KNDemoIO.hh:void from_json(const nlohmann::json& j, CudaGridParams& value);
app/demo-interactor/KNDemoIO.hh:void to_json(nlohmann::json& j, const KNDemoRunArgs& value);
app/demo-interactor/KNDemoIO.hh:void from_json(const nlohmann::json& j, KNDemoRunArgs& value); …
```

Follow "pass-by-pointer" for mutable reference.

---

src/base/DeviceAllocation.cuda.cc
src/base/DeviceAllocation.hh
src/base/DeviceAllocation.i.hh
src/base/DeviceAllocation.nocuda.cc
src/base/DeviceVector.hh
src/base/DeviceVector.i.hh
test/base/DeviceVector.test.cc

I've pulled out this interstitial commit from #131 .
thrust::device_vector has a raw `data()` pointer, and we know that `data()` (messing around with pointers) is always potentially dangerous. To make this safer, I've added function overloads that prevent `make_span`
from accidentally returning a Span to device memory.

Normalize type aliases in DeviceAllocation/DeviceVector and add data()

---

src/CMakeLists.txt
src/physics/em/GammaConversionProcess.cc
src/physics/em/GammaConversionProcess.hh
test/physics/em/BetheHeitler.test.cc
test/physics/em/LivermorePE.test.cc

I missed this during the review for #111 -- the gammas are being produced as a result of annihilation, but the name is confusing next to the positron annihilation process (in which positrons are being annihilated). I suggest changing to "gamma conversion" for consistency with geant4.

Rename gamma annihilation to conversion

---

.gitattributes
CMakeLists.txt
app/demo-interactor/demo-interactor.cc
app/demo-interactor/host-demo-interactor.cc
app/demo-rasterizer/demo-rasterizer.cc
cmake/.gitattributes
cmake/CgvFindVersion.cmake
src/CMakeLists.txt
src/celeritas_version.cc.in
src/celeritas_version.h
test/gtest/detail/TestMain.cc

This uses [a cmake helper script](https://github.com/sethrj/cmake-git-version) to pull git tag and hash information into a configure-time C++ file. Since it only updates the version on the first reconfigure, it's mainly useful for CI and exported releases, but it's a good first step toward versioning output files etc.

Add CMake-derived version metadata to build system and output

---

.jenkins
CMakeLists.txt
cmake/CeleritasUtils.cmake
scripts/build/docker-minimal.sh
scripts/build/docker.sh
scripts/docker/README.md
scripts/docker/ci/Dockerfile

- Add `find_package_handle_standard_args` call for package config files (Geant4, ROOT, VecGeom) that don't do that themselves
- Update docker image to use VecGeom 1.1.11
Needed to fix tests for #90 .

Print HEP package versions during configure, and update CI VecGeom

---

src/physics/base/Model.hh
src/physics/base/PhysicsInterface.hh
src/physics/base/PhysicsParams.cc
src/physics/base/PhysicsStepUtils.hh
src/physics/base/PhysicsStepUtils.i.hh
src/physics/base/PhysicsTrackView.hh
src/physics/base/PhysicsTrackView.i.hh
src/physics/em/EPlusGGMacroXsCalculator.hh
src/physics/em/EPlusGGMacroXsCalculator.i.hh
src/physics/em/EPlusGGModel.cc
src/physics/em/EPlusGGModel.hh
src/physics/em/LivermorePEInterface.hh
src/physics/em/LivermorePEMacroXsCalculator.hh
src/physics/em/LivermorePEMacroXsCalculator.i.hh
src/physics/em/LivermorePEModel.cc
src/physics/em/LivermorePEModel.hh
src/physics/em/LivermorePEParams.hh
src/physics/em/PhotoelectricProcess.cc
src/physics/em/PhotoelectricProcess.hh
src/physics/em/detail/LivermorePE.cu
src/physics/em/detail/LivermorePEInteractor.i.hh
src/physics/em/detail/LivermorePEMicroXsCalculator.hh
src/physics/em/detail/LivermorePEMicroXsCalculator.i.hh
test/CMakeLists.txt
test/physics/base/PhysicsStepUtils.test.cc
test/physics/em/EPlusGG.test.cc
test/physics/em/LivermorePE.test.cc

This add the missing pieces to `calc_tabulated_physics_step` in PhysicsStepUtils.hh (for #125):
* Add macroscopic cross section calculators for the photoelectric effect and positron annihilation models
* Hardwire those processes to compute macro xs on the fly when calculating step length

Complete the implementation of `calc_tabulated_physics_step`

---

src/CMakeLists.txt
src/base/StackAllocatorView.i.hh
src/physics/em/AtomicRelaxation.hh
src/physics/em/AtomicRelaxation.i.hh
src/physics/em/AtomicRelaxationHelper.hh
src/physics/em/AtomicRelaxationHelper.i.hh
src/physics/em/AtomicRelaxationInterface.hh
src/physics/em/AtomicRelaxationParams.cc
src/physics/em/AtomicRelaxationParams.hh
src/physics/em/LivermorePEMacroXsCalculator.i.hh
src/physics/em/LivermorePEModel.cc
src/physics/em/LivermorePEModel.hh
src/physics/em/PhotoelectricProcess.cc
src/physics/em/PhotoelectricProcess.hh
src/physics/em/detail/LivermorePE.hh
src/physics/em/detail/LivermorePEInteractor.i.hh
src/physics/em/detail/Utils.cc
src/physics/em/detail/Utils.hh
test/physics/em/LivermorePE.test.cc

A few additions to atomic relaxation:
- Use a `Stackallocator` to allocate storage for the unprocessed vacancy subshell stack based on the maximum possible size the stack could grow to for each element.
- Add a helper class to bound the maximum possible number of secondaries created based on the actual transition data rather than a hypothetical worst case. On average the number of secondaries produced is closer to 10, so we're usually still allocating much more storage than we need.
- Add the option to set an energy threshold for the production of fluorescence photons and Auger electrons, which can greatly reduce the maximum possible number of secondaries, e.g.:

Atomic relaxation updates

---

src/base/StackAllocatorView.i.hh
src/physics/em/AtomicRelaxationHelper.i.hh
test/sim/TrackInitializerStore.test.hh

Attempting to allocate zero elements using the `StackAllocatorView` was causing the track initializer test to crash (#156). This adds an assertion that the allocation size is greater than zero and fixes the test that was erroneously allocating space for nothing.

Fix allocation of zero elements with StackAllocatorView

---

app/CMakeLists.txt
app/demo-rasterizer/simple-driver.py

Remove the assumption that the build directory is directly inside the source directory. Also fix a missing `f` that led to a bogus filename being written for the rasterizer's debug output.

Improve rasterizer driver

---

test/CMakeLists.txt
test/comm/Logger.test.cc

comm/Logger does benchmarking so must be run by itself.

Fix Logger performance test during heavy loads

---

app/demo-rasterizer/RDemoKernel.cu
src/geometry/GeoTrackView.hh
src/geometry/GeoTrackView.i.hh
src/geometry/LinearPropagator.hh
src/geometry/LinearPropagator.i.hh
test/geometry/GeoTrackView.test.cc
test/geometry/GeoTrackView.test.cu
test/geometry/LinearPropagator.test.cc
test/geometry/LinearPropagator.test.cu

This is a continuation of PR #66, mostling address remaining suggestions from comments there.
- adding a struct to store results from propagation: distance traveled and volume at post-step point
- move all references to geometry away from the LinearPropagator and into GeoTrackView only
- simplify the LinearPropagator interface

Line propagation updates

---

src/base/NumericLimits.hh
src/base/Quantity.hh
src/physics/base/PhysicsStepUtils.i.hh
test/CMakeLists.txt
test/base/NumericLimits.test.cc
test/base/NumericLimits.test.hh

The on-device "inf" and NaN expression are defined by on-device non-constexpr functions and integer constants:
```
./math_constants.h:54:#define CUDART_INF_F            __int_as_float(0x7f800000)
./math_constants.h:91:#define CUDART_INF              __longlong_as_double(0x7ff0000000000000ULL)
```
this meant that the `static constexpr __device__ double infinity()` failed. Thus we cannot label infinity as `constexpr`, which will affect any code that expects to call infinity on device.
I also have sneaked a fix to the geant4 data variables ;)

Fix non-constexpr numeric limits on CUDA device

---

app/CMakeLists.txt
cmake/CeleritasUtils.cmake
src/CMakeLists.txt
test/CMakeLists.txt

The first commit is just to ensure and document that the geometry tests fail when changing the vecgeom link order.

Reduce cmake duplication for linking against vecgeom

---

test/physics/InteractorHostTestBase.hh
test/physics/em/BetheHeitler.test.cc
test/physics/em/EPlusGG.test.cc
test/physics/em/KleinNishina.test.cc
test/physics/em/LivermorePE.test.cc
test/physics/em/MollerBhabha.test.cc
test/physics/em/Rayleigh.test.cc
test/physics/em/SeltzerBerger.test.cc

This implements @whokion 's suggestion of simplifying the diagnostic RNG counters, being more foolproof by resetting the counter when calling `rng()`. (Note though that the RNG stream state itself isn't reset when calling rng.)

Simplify RNG counter reset for physics unit tests

---

src/base/Algorithms.hh
src/physics/em/RayleighModel.cc
src/physics/em/detail/BetheHeitlerInteractor.i.hh
src/physics/em/detail/KleinNishinaInteractor.i.hh
src/physics/em/detail/LivermorePEInteractor.i.hh
src/physics/em/detail/MollerBhabhaInteractor.i.hh
src/physics/em/detail/MollerEnergyDistribution.i.hh
src/physics/em/detail/Rayleigh.hh
src/physics/em/detail/RayleighInteractor.hh
src/physics/em/detail/RayleighInteractor.i.hh
test/base/Algorithms.test.cc
test/physics/em/BetheHeitler.test.cc

Revisit the interactors and ensure that all floating point values are either automatically promoted to `real_type` or wrapped with `real_type`  themselves.
The only change to the "gold" regression values is due to:
```diff
-        } while (BernoulliDistribution(1 - reject_threshold)(rng));
+        } while (!BernoulliDistribution(reject_threshold)(rng));
```
which while mathematically equivalent ends up changing the RNG stream.

Interactor tweaks

---

src/io/AtomicRelaxationReader.cc
src/io/AtomicRelaxationReader.hh
src/io/ImportAtomicRelaxation.hh
src/physics/base/CutoffParams.hh
src/physics/base/CutoffView.hh
src/physics/base/CutoffView.i.hh
src/physics/em/AtomicRelaxation.hh
src/physics/em/AtomicRelaxation.i.hh
src/physics/em/AtomicRelaxationHelper.hh
src/physics/em/AtomicRelaxationHelper.i.hh
src/physics/em/AtomicRelaxationInterface.hh
src/physics/em/AtomicRelaxationParams.cc
src/physics/em/AtomicRelaxationParams.hh
src/physics/em/detail/LivermorePE.cu
src/physics/em/detail/LivermorePEInteractor.hh
src/physics/em/detail/LivermorePEInteractor.i.hh
src/physics/em/detail/MollerBhabha.cu
src/physics/em/detail/MollerBhabhaInteractor.i.hh
test/io/RootImporter.test.cc
test/physics/base/CutoffParams.test.cc
test/physics/em/LivermorePE.test.cc
test/physics/em/MollerBhabha.test.cc

Now that we have production cuts, use `CutoffView` to get the electron and photon energy cutoffs for atomic relaxation. I made a minor change to the `CutoffView` interface so it now constructs the view with the material ID and accepts the particle ID as an argument in the `energy()` and `range()` methods -- this way we don't have to construct a separate view for each particle type. I also moved the structs for the raw imported EADL transition data from the `AtomicRelaxationParams` class to the io/ directory.
Right now on emmet I'm getting the same nvlink error that we saw in #118,
```
nvlink error   : Size doesn't match for '_ZN9celeritas9SecondaryC1Ev$146' in 'src/CMakeFiles/celeritas.dir/physics/em/detail/MollerBhabha.cu.o', first specified in …
```

Use CutoffView in atomic relaxation

---

src/physics/base/PhysicsInterface.hh
src/physics/base/PhysicsParams.cc
src/physics/base/PhysicsParams.hh
src/physics/base/PhysicsStepUtils.hh
src/physics/base/PhysicsStepUtils.i.hh
src/physics/base/PhysicsTrackView.hh
src/physics/base/PhysicsTrackView.i.hh
src/physics/grid/XsCalculator.hh
src/physics/grid/XsCalculator.i.hh
test/physics/base/MockProcess.cc
test/physics/base/MockProcess.hh
test/physics/base/Physics.test.cc
test/physics/base/PhysicsStepUtils.test.cc
test/physics/base/PhysicsTestBase.cc
test/physics/grid/XsCalculator.test.cc

For energy loss processes the post-step energy will be different from the pre-step energy, so the assumption that the cross section is constant along the step is no longer valid. To correctly sample the interaction length, Geant4 uses the "integral approach", which uses MC integration to sample from the exact distribution. At the start of the step, the maximum cross section over the step `xs_max` is estimated and used for the process instead of the cross section at the pre-step energy `E`. At the end of the step, if that process is selected, the cross section is recalculated at the post-step energy `E'` and the discrete interaction occurs with probability `xs(E') / xs_max`.

Correct the sampling of discrete interactions for energy loss

---

src/field/FieldDriver.hh
src/field/FieldDriver.i.hh
src/field/FieldInterface.hh
src/field/FieldParamsPointers.hh
src/field/FieldUtils.i.hh
src/field/RungeKuttaStepper.hh
src/field/RungeKuttaStepper.i.hh
test/CMakeLists.txt
test/field/FieldDriver.test.cc
test/field/FieldDriver.test.cu
test/field/FieldDriver.test.hh
test/field/FieldTestParams.hh
test/field/RungeKutta.test.cc
test/field/RungeKutta.test.cu

This MR, field-driver, 
1) add a magnetic field driver and 
2) update the algorithm to calculate the closest distance between a point and a line-segment
3) evaluate the right hand side of the field equation inside the stepper operator to drop the derivative of the state argument from private methods of the field driver

Magnetic Field Driver

---

src/base/Range.hh
src/base/detail/RangeImpl.hh
src/physics/base/PhysicsStepUtils.i.hh
src/physics/em/AtomicRelaxation.hh
src/physics/em/AtomicRelaxation.i.hh
src/physics/em/detail/LivermorePEInteractor.i.hh
src/physics/em/detail/Rayleigh.cu
src/physics/em/detail/RayleighInteractor.i.hh
src/physics/material/ElementSelector.hh
src/physics/material/ElementSelector.i.hh
src/random/Selector.hh
src/random/Selector.i.hh
test/CMakeLists.txt
test/physics/material/ElementSelector.test.cc
test/random/RngEngine.test.cc
test/random/Selector.test.cc
test/random/SequenceEngine.hh
test/random/SequenceEngine.i.hh

This may be a bit over-engineered, but it abstracts the selection of a discrete PDF that's calculated on-the-fly. I'd intended to use it for the ElementSelector, Livermore, and AtomicRelaxation; but the element selector would be ugly (either re-instantiating the Selector at each sample, or requiring ugly templates to make it class data, or rephrasing it to be a function), and the Livermore/Atomic cases allow a "remainder" for the PDFs -- it's OK if they don't add up to one.
Regardless of those absences, I've implemented the selector in PhysicsStepUtils (which makes the code much cleaner) and replaced the awkward construction in the Rayleigh sampler with the simpler Selector. It is slightly less efficient (requiring one more subtraction) but I can't imagine that being a big deal.
For the …

Add random selector helper class

---

app/geant-exporter/geant-exporter.cc
src/physics/base/PDGNumber.hh
src/physics/base/ParticleParams.cc

Opaque IDs are used as "type-safe indices" everywhere except for PDG code, and are unsigned except for PDG code. We could consider renaming `OpaqueId` after this point.

Use a non-OpaqueId class for PDGNumber

---

src/physics/em/detail/EPlusGGInteractor.i.hh
src/physics/em/detail/KleinNishinaInteractor.i.hh
src/physics/em/detail/SBEnergyDistribution.hh
src/physics/em/detail/SBEnergyDistribution.i.hh
src/random/distributions/ReciprocalDistribution.hh
src/random/distributions/ReciprocalDistribution.i.hh
src/random/distributions/UniformRealDistribution.hh
src/random/distributions/UniformRealDistribution.i.hh
test/CMakeLists.txt
test/random/distributions/ReciprocalDistribution.test.cc

Adds a new distribution for sampling `1/x` on a closed positive interval and replaces three places where hand-rolled versions were previously used.
I verified that the CUDA complier is able to effectively optimize the distribution -- the KN interactor superficially requires an extra `log`, but NVCC reproduces identical PTX code to before the change. The (e+, γγ) kernel changes by replacing a division with a reciprocal+multiplication, potentially offering higher throughput.
Overall this change makes the physics clearer and should not cause any performance regressions.

Add reciprocal distribution

---

src/base/Collection.hh
src/base/CollectionStateStore.hh
src/base/detail/CollectionImpl.hh

@mrguilima encountered wacky build errors as a result of instantiating a `CollectionStateStore` inside a `.cu` file, which isn't a capability I'd intended or anticipated. (It runs afoul of my use of `#ifndef __CUDA_ARCH__` which is designed just to keep C++ headers from propagating into the NVCC device kernel and slow builds down.) Although we might remove those preprocess definitions in the future, this will at least give nice failure messages (static assertions rather than "declared but not defined"  classes).

Document and improve failure mode for collections in cu code

---

app/CMakeLists.txt
app/demo-loop/LDemoParams.cc
interface/celeritas.i
src/io/ImportParticle.hh
src/physics/base/PhysicsTrackView.i.hh
test/geometry/GeoMaterial.test.cc
test/io/RootImporter.test.cc
test/physics/em/ImportedProcesses.test.cc

Apple-clang on my mac pointed out some misuses of `std::move`, and there were a few other minor issues stemming from recent merges.

Clang and documentation fixes

---

app/CMakeLists.txt
app/demo-loop/simple-driver.py
app/demo-loop/simple_cms.gdml

This PR adds the geometry described in issue #187 to the `demo-loop` and updates its `simple-driver.py` to run `geant-exporter` and produce the root file before starting the demo app.

Add single-material cms mock-up geometry to the demo-loop 

---

src/base/DeviceAllocation.cc
src/physics/base/PhysicsParams.cc
src/physics/em/ComptonProcess.hh
src/physics/em/EPlusAnnihilationProcess.cc
src/physics/em/EPlusAnnihilationProcess.hh
src/physics/em/EPlusGGModel.cc
src/physics/em/GammaConversionProcess.cc
src/physics/em/GammaConversionProcess.hh
src/physics/grid/ValueGridBuilder.cc
src/physics/grid/ValueGridBuilder.hh
test/CMakeLists.txt
test/base/DeviceAllocation.test.cc
test/physics/base/Physics.test.cc
test/physics/em/BetheHeitler.test.cc
test/physics/em/ImportedProcesses.test.cc

The annihilation/conversion processes were basically stub files. This adds a new "value grid builder" to support the OTF-only positron annihilation process, and couples the gamma conversion to the import data.

Complete positron annihilation and gamma conversion processes

---

.jenkins
scripts/docker/build.sh
src/geometry/GeoParams.cc
src/geometry/GeoTrackView.hh
src/geometry/GeoTrackView.i.hh
test/geometry/Geo.test.cc
test/geometry/LinearPropagator.test.cc

As discussed in today's (May 6) physics hackathon, the GeoParams and GeoTrackView interfaces are being modified to return logical volumes rather than physical volumes.  For example:
- GeoParams::num_volumes() now returns the number of logical volumes 
- GeoParams::id_to_label() and label_to_id() now return the label or id of that logical volume
- GeoTrackView::volume() and volume_id() now return the logical volume (and its ID) containing the current track
Geometry tests were adapted to the new volume IDs.
*Note:* updated version of VecGeom required - https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/816

Use logical instead of placed volumes for VolumeId

---

src/base/Algorithms.hh
src/physics/em/detail/SBEnergyDistHelper.hh
src/physics/em/detail/SBEnergyDistHelper.i.hh
src/physics/em/detail/SBEnergyDistribution.hh
src/physics/em/detail/SBEnergyDistribution.i.hh
src/physics/em/detail/SeltzerBerger.cu
src/physics/em/detail/SeltzerBergerInteractor.hh
src/physics/em/detail/SeltzerBergerInteractor.i.hh
src/random/distributions/ReciprocalDistribution.hh
src/random/distributions/ReciprocalDistribution.i.hh
test/physics/em/SeltzerBerger.test.cc

This refactors the SB energy distribution into two parts:
- a non-templated component that sets up the energy sampling function and calculates the bounding cross section; and
- a component templated on a "correction factor" that samples an energy, gets the cross section at that energy from the non-template component and multiplies by a scaling factor (1 for electrons, the result of `SBPositronXsCorrector` for positrons), and rejects based on a random number and the maximum (scaled) cross section.
I added tests that demonstrate:
- nothing about the electron sampling changes
- the sampling efficiency does not change for a constant non-unity value for the scaling factor
- the sampling efficiency decreases slightly for positrons (since the scaled cross section shape is more pronounced/less …

Add positron correction for SB sampling

---

test/CMakeLists.txt
test/random/curand/CurandPerformance.test.cc
test/random/curand/CurandPerformance.test.cu
test/random/curand/CurandPerformance.test.hh

Added a simple test to compare computing performance of popular cuda random number generators on both CPU and GPU -
the test was used to measure performance of curand generators summarized in Issues #183 (Examine 
RNG quality and performance).

Computing performance tests of curand generators

---

src/field/FieldDriver.i.hh
src/field/FieldPropagator.i.hh
test/field/FieldPropagator.test.cc
test/field/FieldTestBase.hh
test/field/detail/CMSParameterizedField.hh
test/field/detail/CMSParameterizedField.i.hh

This MR includes
- Improved the logic to find the intersection point and associated updates for boundary crossing tests with a smaller delta_intersection
- Fixed the logic to find the next chord in the FieldDriver class
- Added function const qualifier in CMSParameterizedField

Updates for Field Propagation

---

app/demo-loop/simple-driver.py
src/base/Span.hh
src/comm/Device.hh
test/base/StackAllocator.test.cu
test/geometry/Geo.test.cu
test/geometry/LinearPropagator.test.cu

A few of the CUDA tests use `thrust::host_vector`. In previous versions of CUDA, `host_vector` was forward declared in `thrust/device_vector.h`, so including that was sufficient, but in the latest CUDA this is no longer true so an explicit `#include <thrust/host_vector.h>` is needed to avoid build errors. I also fixed a few typos I came upon.

Fix a few missing includes and typos

---

app/CMakeLists.txt
app/demo-loop/simple-driver.py
src/base/ScopedStreamRedirect.hh
src/io/EventReader.cc

This PR enables the demo-loop app test to run in CI and fixes a few issues @vrpascuzzi and I have encountered with recent builds:
- HepMC3 spits out some diagnostic output that interferes with the expected JSON output in simple-driver.py.
- The storage factor for secondaries is not sufficiently high to complete all steps in the demo-loop app. Bumping it up to 10 seems to work on my setup :crossed_fingers:

Enable demo-loop app test in CI

---

src/sim/detail/InitializeTracks.cu

While working on the CPU demo loop, I ran across what I believe to be a bug. In the `init_tracks` kernel, we initialize the geometry state but never use the result to initialize the material state. When later kernel calls try to access the material state, the following behavior is observed:
- On GPU, the material states (material IDs, to be specific) are never set and default to zero by virtue of being backed by a `DeviceVector`. Thus, the demo loop continues fine with particles appearing to always be in the material with ID 0.
- On CPU, the material states are backed by a `std::vector`, so the default constructor of `MaterialId` is called, which sets the values to `OpaqueId::invalid_value()`. Once the demo loop gets to a kernel that requires material states, it correctly aborts at this …

Make sure init_tracks kernel initializes material state

---

app/geant-exporter/CeleritasG4Version.hh
app/geant-exporter/ImportProcessConverter.cc
app/geant-exporter/geant-exporter.cc

This allows building _Celeritas_ with Geant4 v11, which is needed for _Acceleritas_.
Three main changes are added to the code to enable the compatibility between G4 versions and are selected via C++ macros:
- G4 v11 replaces `G4RunManager` by `G4RunManagerFactory`.
- `G4PhysicsVectorType` enum is simpler in G4 v11.
- A few physics tables are deleted in G4 v11.

Add Geant4 v11 compatibility to geant-exporter

---

src/physics/em/detail/BetheHeitler.cu

Right now, we are passing an `ElementView` temporary to the constructor of `BetheHeitlerInteractor`, where it is bound to a const reference member variable. Binding a temporary to a const reference member variable does not extend the lifetime of the temporary, which means that by the time we reach `operator()`, that temporary may no longer exist. This is why the CPU demo loop test is [failing](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Celeritas/detail/PR-273/1/tests) with an error in `BetheHeitlerInteractor::operator()`.

Fix bug in element use in BetheHeitlerInteractor

---

app/demo-loop/KernelUtils.hh
app/demo-loop/KernelUtils.i.hh
app/demo-loop/LDemoKernel.cu
src/geometry/GeoMaterialView.hh
src/physics/base/Interaction.hh
src/sim/Action.hh
src/sim/detail/InitializeTracks.cu
test/geometry/GeoMaterial.test.cc

This fixes a few more bugs in the demo loop/track initialization:
- The physics state was not being initialized when a new track was created from a secondary in the parent track's slot in `locate_alive_kernel()`.
- The material state was not being updated when a particle entered a new volume in `move_and_select_model()`. To simplify this fix I modified the `GeoMaterialView` interface so the volume ID is passed as an argument to the `material_id()` method instead of to the constructor.
- The `Interaction` was not being reset at the end of a step after the state change and secondaries had been processed. In most cases (boundary crossings, discrete interactions, spawned tracks) the `action` would be updated correctly in the next step and this wouldn't matter. However, in a couple cases …

A few more demo loop fixes

---

src/base/OpaqueId.hh
test/base/OpaqueId.test.cc

This is an attempted workaround for a conflict with `PTL::Thread` when including both Celeritas and Geant4 (v11b) that looks like it results from an errant `using` bringing that typedef into the global scope.
```
from acceleritas/app/g4hpc/src/UserTaskManager.cc:10:
acceleritas/external/celeritas/src/base/OpaqueId.hh:121:34: error: using typedef-name ‘PTL::Thread’ after ‘struct’
using ThreadId = OpaqueId<struct Thread>;
^~~~~~
In file included from geant4.11.beta/source/externals/ptl/include/PTL/AutoLock.hh:246,
from geant4.11.beta/source/externals/ptl/include/PTL/VTask.hh:32,
from geant4.11.beta/source/externals/ptl/include/PTL/Task.hh:34,
from geant4.11.beta/source/externals/ptl/include/PTL/TaskGroup.hh:35,
from acceleritas/app/g4hpc/include/UserTaskManager.hh:10,
from …
```

Explicitly declare Thread to avoid Geant4 conflict

---

app/demo-loop/simple-driver.py
src/base/CollectionBuilder.hh
src/base/CollectionBuilder.i.hh
src/geometry/detail/VGNavCollection.cc
src/geometry/detail/VGNavCollection.hh
src/physics/em/detail/SeltzerBergerInteractor.i.hh

This PR changes `VGNavCollection<..., host>` to hold a collection of navigation states. I originally hoped to use NavStatePool directly from VecGeom but if I'm not mistaken, it looks like it's hardwired to be used on GPU. To build the collection of navigation states (each of which is a unique_ptr), I had to add an overload for `CollectionBuilder::push_back(T&&)`.
Now that CPU code can handle multiple primaries instead, I ran the demo loop to completion and get slightly below 15 GeV of energy deposited (as expected, accounting for the bug with positron production cutoff) with the same distribution as observed on GPU.

Allow multiple VecGeom navigation states on host

---

src/physics/em/EnergyLossDistribution.i.hh

When running the simple CMS problem on CPU with a debug build, I ran into a case where we were getting exactly zero energy loss in `EnergyLossDistribution::sample_urban`, and right now we have `CELER_ENSURE(result > 0)`. After some discussion with @amandalund, it sounds like exactly zero energy loss is possible and should be allowed.

Allow exactly zero energy loss in Urban model for energy loss fluctuation

---

src/base/Array.hh
src/orange/surfaces/SurfaceAction.hh
src/orange/surfaces/detail/SurfaceAction.hh
test/orange/surfaces/GeneralQuadric.test.cc
test/orange/surfaces/Sphere.test.cc
test/orange/surfaces/SurfaceAction.test.cc

- Define new helper function that doesn't require a Surfaces instance
(useful during construction)
- Refactor surface action to use C++14 decltype(auto)
- Remove nonstandard Array::extent

Add static surface actions for ORANGE

---

app/demo-loop/simple-driver.py
src/physics/em/detail/BetheHeitlerLauncher.hh
src/physics/em/detail/LivermorePELauncher.hh
src/physics/em/detail/MollerBhabhaLauncher.hh

Right now, the CPU solver crashes if you use more track states than we have primaries. After some debugging, I found that this was a result of some of the interactors trying to create `CutoffView` with an invalid material (because the track was not active). Just making sure that we check for a matching physics model before instantiating `CutoffView` fixes this. With an arbitrary number of tracks allowed on CPU now, I've changed simple-driver.py to use the same number of tracks and storage factor for CPU and GPU. Everything agrees nicely — with max_num_tracks=4096, they both take 102 steps to finish and result in 15 GeV of energy deposition.

Allow arbitrary number of tracks on CPU

---

app/CMakeLists.txt
app/demo-loop/LDemoKernel.cc
cmake/CeleritasUtils.cmake
scripts/dev/gen-interactor.py
src/CMakeLists.txt
src/base/Atomics.hh
src/comm/Device.cc
src/physics/em/generated/BetheHeitlerInteract.cc
src/physics/em/generated/EPlusGGInteract.cc
src/physics/em/generated/KleinNishinaInteract.cc
src/physics/em/generated/LivermorePEInteract.cc
src/physics/em/generated/MollerBhabhaInteract.cc
src/physics/em/generated/MuBremsstrahlungInteract.cc
src/physics/em/generated/RayleighInteract.cc
src/physics/em/generated/SeltzerBergerInteract.cc

This PR adds OpenMP threading for most steps of the demo loop: `pre_step`, `along_and_post_step`, `launch_models` (or rather, the individual interactors), and `process_interactions`. On our small test problem with only 15 primaries, the runtime is not long enough to notice any difference. I used @stognini's nifty hepmc3 generator to create a hepmc3 file with 100 events each having 10 primaries and then ran it to completion. I placed some stopwatches in the main demo loop just to get some timing data and obtain the following with OMP_NUM_THREADS=1:
```
status: init_tracks             = 0.831755 s
status: pre_step                = 9.20099 s
status: along_and_post_step     = 6.06276 s
status: interactors             = 3.54098 s
status: process                 = 0.986288 s
status: …
```

Add OpenMP threading for CPU demo loop

---

app/demo-loop/LDemoIO.cc
app/demo-loop/LDemoIO.hh
app/demo-loop/LDemoKernel.cu
app/demo-loop/demo-loop.cc
src/physics/em/BremsstrahlungProcess.hh
src/physics/em/RelativisticBremModel.cc

This MR includes several minor updates:
- Moved build_transporter from demo-loop.cc to LDemoIO which helps to reuse the function from acceleritas
- Corrected and removed comment lines
- Removed a unused variable

Refactor transporter construction and fix comments

---

app/demo-loop/LDemoIO.cc
app/demo-loop/LDemoIO.hh
src/physics/em/BremsstrahlungProcess.cc
src/physics/em/BremsstrahlungProcess.hh
src/physics/em/CombinedBremModel.cc
src/physics/em/RelativisticBremModel.cc
src/physics/em/SeltzerBergerModel.cc
src/physics/em/detail/CombinedBremInteractor.i.hh
src/physics/em/detail/PhysicsConstants.hh
src/physics/em/detail/RBEnergySampler.i.hh
src/physics/em/detail/RelativisticBremData.hh
src/physics/em/detail/RelativisticBremInteractor.i.hh
test/physics/em/ImportedProcesses.test.cc

The MR includes
- add RelativisticBremModel and CombinedBremModel to BremsstrahlungProcess with BremsstrahlungOptions
- use energy limits of Bremsstrahlung models consistently for their applicability
- use the combined Bremsstrahlung model and the LPM effect as the default option
but does not include the run-time argument setting in the python driver for the demo-loop as there may have a centralized control for different physics options later.

Integration of multiple bremsstrahlung models

---

src/physics/em/detail/CombinedBremInteractor.hh
src/physics/em/detail/CombinedBremInteractor.i.hh
src/physics/em/detail/RBEnergySampler.hh
src/physics/em/detail/RBEnergySampler.i.hh
src/physics/em/detail/SeltzerBergerInteractor.hh
src/physics/em/detail/SeltzerBergerInteractor.i.hh

Found a few unused variables during PR #326 that prevent Celeritas from compiling when cmake warnings are treated as errors. These changes are being resolved here as a separate PR.

Remove unused variables

---

app/demo-rasterizer/RDemoKernel.cu
app/demo-rasterizer/RDemoRunner.cc
app/demo-rasterizer/RDemoRunner.hh
app/demo-rasterizer/demo-rasterizer.cc
src/geometry/GeoParams.cc
src/geometry/GeoTrackView.hh
src/geometry/GeoTrackView.i.hh
src/geometry/detail/BVHNavigator.hh
test/geometry/Geo.test.cc
test/geometry/Geo.test.cu
test/geometry/LinearPropagator.test.cc

I have compared rasterizer processing times (cms2018 geometry), between VecGeom's SimpleNavigator and AdePT's BVHNavigator, and BVH is faster by a factor between 2x and 4x, depending on the rasterization plane.
* Summary for BVH navigator performance:
- xyview:  Average time: 0.285370 s
- xyview-off:  Average time: 0.441714 s
- xzview-off:  Average time: 0.313924 s
- yzview-off:  Average time: 0.313924 s
* Summary for vecgeom's SimpleNavigator:
- xyview-off:  Average time: 1.613710 s
- xzview-off:  Average time: 0.611025 s
- yzview-off:  Average time: 0.601223 s
The -off suffix means that an offset is applied to the third coordinate, otherwise there's a higher chance of some tracks getting stuck.

Use BVH navigator by default

---

app/demo-loop/diagnostic/StepDiagnostic.hh
app/demo-loop/diagnostic/StepDiagnostic.i.hh

I neglected to update the indexing in a couple places when I added bins for underflow and overflow to the `StepDiagnostic` -- fixed here.

Fix indexing in step diagnostic

---

src/base/Algorithms.hh
test/physics/em/RelativisticBrem.test.cc

Fixes the error @pcanal pointed out in #325 and a small precision difference in the brems test when running with `-march=native` in highly optimized mode on CPU. Happy Christmas!

Fix tolerance and missing move

---

src/orange/Data.hh
src/orange/universes/SimpleUnitTracker.hh
src/orange/universes/detail/SurfaceFunctors.hh
src/orange/universes/detail/Types.hh
src/orange/universes/detail/Utils.hh
test/orange/OrangeGeoTestBase.cc
test/orange/OrangeGeoTestBase.hh
test/orange/universes/SimpleUnitTracker.test.cc
test/orange/universes/SimpleUnitTracker.test.cu
test/orange/universes/SimpleUnitTracker.test.hh

This implements distance-to-boundary calculations for single universes. There are two algorithms for finding the nearest surface crossing. The first is the "simple" one, where crossing any boundary exits the volume. In that case, the closest nonzero distance points to the target surface. The second "complex" algorithm effectively tracks through the internal surfaces in order (by sorting) until outside the volume. Unlike the CPU implementation of ORANGE in SCALE, this implementation sorts surfaces using an intermediate indirection array of face IDs.
We should consider as an optimization the option of specifying a "maximum" intersection distance, allowing us to reduce the number of surfaces considered in the sort and in the boundary crossing.

ORANGE: implement distance-to-boundary calculation

---

app/CMakeLists.txt
app/demo-loop/KernelUtils.i.hh
app/demo-loop/LDemoIO.cc
app/demo-loop/simple-cms.gdml
app/demo-loop/simple-cms.org.json
app/demo-loop/simple-cms.org.omn
app/demo-loop/simple-driver.py
src/geometry/GeoMaterialParams.cc
src/orange/OrangeTrackView.hh
test/orange/Orange.test.cc

- Fix (and add tests for) missing write-on-destruct for ORANGE track view
- Fix material mapping in demo loop
- Update CMS model to remove pointer addresses, and add ORANGE JSON input
- Use JSON file instead of GDML if VecGeom is disabled
Closes #267

Enable ORANGE demo loop

---

app/demo-loop/demo-loop.cc
src/CMakeLists.txt
src/base/Assert.cc
src/base/ColorUtils.cc
src/comm/Device.cc
src/comm/Environment.cc
src/comm/Environment.hh
src/comm/EnvironmentIO.json.hh
src/comm/Logger.cc
src/comm/ScopedMpiInit.cc
src/io/AtomicRelaxationReader.cc
src/io/LivermorePEReader.cc
src/io/SeltzerBergerReader.cc
test/CMakeLists.txt
test/comm/Environment.test.cc
test/comm/Logger.test.cc
test/field/detail/CMSFieldMapReader.cc
test/field/detail/CMSFieldMapReader.hh
test/gtest/detail/TestMain.cc

This lets us control environment variables as part of the input, and get a copy of the variables accessed by Celeritas for verification purposes.

Add abstraction for environment variables to support JSON I/O

---

src/base/Collection.hh
src/base/Range.hh
src/base/Span.hh
src/base/detail/RangeImpl.hh
src/orange/surfaces/Surfaces.hh
test/CMakeLists.txt
test/field/data/field-test.org.json
test/field/data/field-test.org.py

The bug @paulromano discovered in the OrangeTrackView in #343 was responsible for the failures in the ORANGE version of the Field propagator test. (Oops!) This PR adds the ORANGE geometry version of those problems.
Also, with some rudimentary profiling of the debug version of the code I found that force-inlining some of the low-level functions in Range, Span, and Collection improves the debug-build performance by 20% for the field test (1.2s -> 1s). I expect no performance change for the release build since presumably the compiler should inline those functions automatically. Since the primary changes are nearly-trivial constructors the force-inlines should not negatively impact the ability to debug the code.

Enable ORANGE field test

---

app/demo-loop/LDemoIO.cc
app/demo-loop/LDemoIO.hh
app/demo-loop/Transporter.cc
app/demo-loop/Transporter.hh
app/demo-loop/Transporter.json.hh
app/demo-loop/demo-loop.cc
app/demo-loop/simple-driver.py
app/demo-rasterizer/demo-rasterizer.cc
scripts/docker/ci/run-ci.sh
src/orange/OrangeTrackView.hh

- Add 'active' for post-initialize alive count
- Total time is just for transport; additional 'setup' time for problem  creation (VecGeom, ROOT)
- Fix early termination of cpu-demo-loop due to step count
- Rename output keys from demo loop
- Un-nest input parameters

Add status messages and improve diagnostics to demo loop

---

src/base/detail/CollectionImpl.hh
src/physics/base/Interaction.hh
src/sim/detail/LocateAliveLauncher.hh
src/sim/detail/ProcessSecondariesLauncher.hh
test/sim/TrackInit.test.cc
test/sim/TrackInit.test.cu
test/sim/TrackInit.test.hh

The parent IDs of the tracks are currently not set correctly: because a secondary is immediately initialized in the parent track’s slot if the parent was killed, any other secondaries produced by that track actually have a "sibling" ID as their parent ID. This fixes the parent IDs and moves the immediate initialization of a secondary to the same kernel where the track initializers are created. All newly initialized tracks now also have the correction "spawned" `Action`. I added a check for the parent IDs in the track initialization test and simplified the collection of results (use `Collection`s to copy state data from device to host instead of launching kernels to extract the data).

Fix parent ID assignment

---

src/base/DeviceAllocation.cc
src/base/DeviceAllocation.hh

The number of bytes to allocate on device calculated in `DeviceVector` is converted from `std::size_t` to `celeritas::size_type` in the `DeviceAllocation` constructor. This was causing errors when running larger demo loop problems on device because too little memory was being allocated for large arrays.

Use size_t in DeviceAllocation

---

test/sim/TrackInit.test.cc
test/sim/TrackInit.test.cu
test/sim/TrackInit.test.hh

The loop in the TrackInit secondaries test currently terminates when there are no queued initializers, but since secondaries are produced at each iteration there will _always_ be initializers. The loop was actually exiting when there was no space left in the `StackAllocator` to create new secondaries (I ran into this when preallocating one of the secondaries in the `Interaction` -- this resulted in an infinite loop because the `StackAllocator` was never used). This updates the test so the loop will terminate after a fixed number of iterations.

Fix TrackInit test

---

src/sim/TrackData.hh
src/sim/detail/InitTracksLauncher.hh

This makes sure the `Interaction`s are initialized at the start of the simulation, as some members (`secondaries`) might otherwise be used uninitialized. This could possibly be the cause of the demo-loop error seen in #374.

Initialize interactions on device

---

src/orange/OrangeTrackView.hh
src/vecgeom/VecgeomTrackView.hh
test/orange/Orange.test.cc
test/vecgeom/Vecgeom.test.cc

@whokion I saw you had to disable the UrbanMsc test when vecgeom is disabled, which reminded me that we didn't update the ORANGE interface to have a safety distance. I realized as I was modifying the class that the `safety` method now is really a `find_safety` since it's not a mere accessor, so I'd like to change it to that (and mark it as non-const since it could require the use of temporary state memory to calculate). With this change you should be able to keep your test as `GeoTrackView` but simply disable it from running when vecgeom is disabled (using a mechanism similar to the `_needs_hepmc` in the test/CMakeLists.txt).

Rename safety to find_safety and add not-implemented ORANGE interface

---

app/demo-rasterizer/RDemoKernel.cu
scripts/cmake-presets/yuri.json
src/field/FieldPropagator.hh
src/geometry/LinearPropagator.hh
src/orange/Data.hh
src/orange/OrangeParams.cc
src/orange/OrangeTrackView.hh
src/orange/construct/VolumeInput.hh
src/orange/construct/VolumeInputIO.json.cc
src/orange/construct/VolumeInserter.cc
src/orange/surfaces/detail/QuadraticSolver.hh
src/orange/universes/SimpleUnitTracker.hh
src/orange/universes/VolumeView.hh
src/orange/universes/detail/SurfaceFunctors.hh
src/orange/universes/detail/Types.hh
src/orange/universes/detail/Utils.hh
src/vecgeom/VecgeomTrackView.hh
test/field/FieldPropagator.test.cc
test/orange/Orange.test.cc
test/orange/OrangeGeoTestBase.cc
test/orange/universes/SimpleUnitTracker.test.cc
test/vecgeom/Vecgeom.test.cc
test/vecgeom/Vecgeom.test.cu

The key changes are:
- ORANGE no longer stores a local copy of the thread state; it accesses directly from global memory
- A new "find_distance" method with a maximum step length has been implemented for both VecGeom and ORANGE
- ORANGE quadrics no longer return intercepts of zero, simplifying some logic for removing invalid intersections
- In the ORANGE intersection method, instead of saving all distances and then later removing  the infinite ones, we now only save the finite (or "nearby" if calling with maximum step length) ones
- The find methods now return `Propagation` to indicate if a boundary was encountered.
Removing the local copy of the thread state substantially reduced register pressure (especially on Crusher) and improves occupancy on wildstyle's `process_interactions` and …

Optimize geometry tracking

---

app/demo-loop/LDemoLauncher.hh
app/demo-loop/Transporter.cc
app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh
app/demo-loop/diagnostic/StepDiagnostic.hh
src/sim/SimData.hh
src/sim/SimTrackView.hh
src/sim/detail/ProcessSecondariesLauncher.hh

This adds a step counter to the sim state data. The multiple scattering step limitation algorithm treats the first step of a track differently; this change will allow us to determine if a track was just initialized.
I also modified the `StepDiagnostic` to use this step count and rearranged the demo loop diagnostics slightly (`Diagnostic::mid_step` is now called after `process_interactions`, which will also be necessary for the MC truth diagnostic). I verified that the diagnostic results for the medium input are unchanged.

Store the number of steps per track

---

CMakePresets.json
app/CMakeLists.txt
cmake/CeleritasAddTest.cmake
scripts/cmake-presets/ci.json
scripts/cmake-presets/crusher.json
scripts/dev/run-cloc.sh
scripts/docker/README.md
scripts/docker/ci/launch-local-test.sh
scripts/docker/ci/run-ci.sh
src/base/Assert.hh
src/base/KernelParamCalculator.device.hh
test/CMakeLists.txt

Splitting out some non-kernel-related changes from #380 since @tmdelellis and I are trying to understand what those launch parameters are doing...
The main change here is that Stopwatch no longer runs under valgrind because of timing issues (the "pause" time can be more than 10% of the requested pause time).

Add ctest labels, minor tweaks

---

src/vecgeom/VecgeomTrackView.hh
src/vecgeom/detail/BVHNavigator.hh
src/vecgeom/detail/VecgeomNavCollection.hh
test/vecgeom/Vecgeom.test.cc

This commit fixes the safety tests, by using the same BVH and safety algorithms for host and device.
Previous references to NavStateIndex had to be replaced by a common alias, NavigationState, which points to either NavStatePath or NavStateIndex, depending on the NAVINDEX configuration.  
This commit also re-enables the part of the test that was previously broken.

Go back to always using the BVH navigator for VecGeom-based tracking

---

app/demo-loop/LDemoIO.cc
app/demo-loop/LDemoIO.hh
app/demo-loop/LDemoLauncher.hh
app/demo-loop/Transporter.cc
app/demo-loop/Transporter.hh
app/demo-loop/diagnostic/EnergyDiagnostic.hh
app/demo-loop/simple-driver.py
src/sim/detail/InitTracksLauncher.hh

- Ability to disable Rayleigh
- Ability to switch energy deposition axis and change grid via input
- Fix for energy deposition when the end point is coincident with the edep grid (moving back half a step because energy would be placed in the wrong bin at the end of a geometry-limited step)
- Optimization for energy deposition (we're atomic-adding zeroes to a bunch of never-alive tracks)

Add features and fixes for testem3 comparison

---

CMakeLists.txt
scripts/cmake-presets/wildstyle.json

Geant4 forcibly adds `include_directories(CLHEP_INCLUDE_DIRS)` inside the FindGeant4 recipe. This results in code that *doesn't even link against Geant4* to include the CLHEP directories, which (see https://github.com/drbenmorgan/CLHEP/pull/1 ) use relative paths that result in bad diagnostic messages, since unrelated packages in a spack view look like they're coming from something related to CLHEP:
```
/spack/environments/celeritas/.spack-env/view/lib/CLHEP-2.4.5.1/../../include/gtest/gtest.h:299:9: error: no viable conversion from 'const celeritas::Interaction' to 'bool'
```
The guilty line:
https://github.com/Geant4/geant4/blob/de4f28d823f824725898d2ee37aaca96b10a1386/cmake/Templates/Geant4Config.cmake.in#L260

Work around Geant4 include propagation

---

src/field/FieldDriver.hh

@whokion discovered this a couple of months ago while I was writing a unit test. I intended to merge it with that unit test, but it hasn't happened yet—so let's get it in now. I also replaced the fixed `min(max(v, lo), hi)` with the recently introduced `clamp(v, lo, hi)`.

Fix error in FieldDriver

---

src/field/HelixStepper.hh
src/field/MagFieldEquation.hh
src/field/UniformZMagField.hh
src/field/ZHelixStepper.hh
test/field/FieldDriver.test.cc
test/field/FieldDriver.test.cu
test/field/FieldPropagator.test.cc
test/field/FieldPropagator.test.cu
test/field/Steppers.test.cc
test/field/Steppers.test.cu
test/field/Steppers.test.hh

This MR includes:
- Add an explicit helix stepper (exact solution with a uniform magnetic field)
- Consolidate stepper tests
- Use DormandPrinceStepper for testing FieldPropagator and FieldDriver

Add a Helix stepper

---

test/field/FieldPropagator.test.cc
test/field/FieldPropagator.test.cu
test/field/FieldPropagatorTestBase.hh
test/field/Steppers.test.cc
test/field/UserField.test.hh
test/field/UserMapField.test.cc
test/field/UserMapField.test.cu
test/field/UserParamField.test.cc
test/field/UserParamField.test.cu

This MR extends existing tests for field propagation and boundary crossing with user defined non-uniform magnetic fields:
- UserParamField.test with CMSParameterizedField.
-  UserMapField.test with CMSMapField.
and
-  Move FieldPropagatorTestBase in a separate header in order to reuse it for other tests.
Both tests may be compactified further as they are using similar codes with minor variations from FieldPropagator.test, which may be done in a separate MR later.

Extend user defined magnetic field tests

---

app/demo-loop/Transporter.hh
app/demo-loop/Transporter.json.hh
app/demo-loop/demo-loop.cc
app/demo-loop/simple-driver.py
src/CMakeLists.txt
src/base/EnumArray.hh
src/celeritas_cmake_strings.h.in
src/comm/BuildOutput.cc
src/comm/BuildOutput.hh
src/physics/base/PhysicsParams.cc
src/physics/base/PhysicsParamsOutput.cc
src/physics/base/PhysicsParamsOutput.hh
src/sim/ActionManager.cc
src/sim/ActionManager.hh
src/sim/ActionManagerOutput.cc
src/sim/ActionManagerOutput.hh
src/sim/JsonPimpl.hh
src/sim/OutputInterface.cc
src/sim/OutputInterface.hh
src/sim/OutputInterfaceAdapter.hh
src/sim/OutputManager.cc
src/sim/OutputManager.hh
test/CMakeLists.txt
test/physics/base/Physics.test.cc
test/sim/ActionManager.test.cc
test/sim/OutputManager.test.cc

This defines an interface for saving certain output to JSON. It's sort of an abstraction of what we output in the demo loop, and it can be extended to other system diagnostic data and outputs. The integration into the demo loop is hacky at the moment, but as the loop gets refactored into the main source code I think it will be cleaner.

Add output manager

---

src/base/Constants.hh
test/CMakeLists.txt
test/base/Constants.test.cc

Inspired by https://github.com/celeritas-project/celeritas/pull/401#discussion_r843322695 I want to make sure the constants that we see in Geant4 don't have mysterious multipliers. There are three CLHEP constants that seem to have some unusual non-SI units built in:
```
/rnsdhpc/code/celeritas/test/base/Constants.test.cc:94: Failure
Value of: CLHEP::amu
Actual: 0.010364268824678106
Expected: atomic_mass
Which is: 1.6605390666e-24
(Absolute error 0.010364268824678106 exceeds tolerance 1.0000000000000001e-09)
/rnsdhpc/code/celeritas/test/base/Constants.test.cc:95: Failure
Value of: CLHEP::epsilon0
Actual: 55263493610.6576
Expected: eps_electric
Which is: 8.8541878128000001e-21
(Absolute error 55263493610.6576 exceeds tolerance 1.0000000000000001e-09) …
```

Add CLHEP/Celeritas constant conversion tests

---

src/celeritas/em/distribution/UrbanMscScatter.hh
test/celeritas/em/UrbanMsc.test.cc

This MR includes a couple of bug fixes in UrbanMscScatter.hh
- Replaced `true_path <= input_.limit_min` by `true_path_ <= shared.params.limit_min_fix() `for one of conditions for skipping MSC sampling
- Reordered `sample_cos_theta` before sampling the lateral displacement as `tau_` should be updated beforehand.
- Updated expected values after above fixes

Msc Update: A couple of bug fixes in MSC samplings

---

src/CMakeLists.txt

ROOT's `root_generate_dictionary` function only installs the `rootmap`/`rdict.pcm` files whenever `CMAKE_LIBRARY_OUTPUT_DIRECTORY` is set (which it by default is not). Install those files manually to avoid warnings such as
```
Error in <TCling::LoadPCM>: ROOT PCM ..../celeritas/install/celeritas/lib64/libceleritas_io_rdict.pcm file does not exist
```

Install rootmap/pcm files

---

app/CMakeLists.txt
src/celeritas/em/data/UrbanMscData.hh
src/celeritas/em/distribution/UrbanMscScatter.hh
src/celeritas/em/distribution/UrbanMscStepLimit.hh
src/celeritas/ext/VecgeomTrackView.hh
src/celeritas/global/detail/AlongStepActionImpl.hh
src/celeritas/phys/Interaction.hh
src/orange/OrangeTrackView.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/ext/Vecgeom.test.cc
test/orange/Orange.test.cc

As we discussed, the original `find_safety` track function was slightly over-engineered: we only ever calculate the safety from the current position. Simplify the interfaces for `find_safety` as well as the `UrbanMscStepLimit` class.
---
Additionally, prevent negative safety distances from VecGeom (this was apparently happening: we need more assertions!) and update `UrbanMscStepLimit` so that if we *do* get negatives they'll implicitly be treated like zeros.

Simplify and fix safety/MSC

---

app/demo-loop/Transporter.cc
src/CMakeLists.txt
src/celeritas/ext/detail/DetectorConstruction.cc
src/celeritas/field/RungeKuttaStepper.hh
src/celeritas/global/ActionManagerOutput.cc
src/celeritas/global/CoreTrackData.hh
src/celeritas/phys/PhysicsParams.cc
src/celeritas/phys/PhysicsParams.hh
src/celeritas/phys/PhysicsStepView.hh
src/celeritas/phys/PhysicsTrackView.hh
src/celeritas/random/CuHipRngData.hh
src/celeritas/random/Selector.hh
src/celeritas/track/detail/ProcessSecondariesLauncher.hh
test/celeritas/em/SeltzerBerger.test.cc
test/celeritas/field/FieldDriver.test.cc
test/celeritas/field/FieldPropagator.test.cc
test/celeritas/field/FieldPropagator.test.cu
test/celeritas/field/FieldPropagator.test.hh
test/celeritas/field/Steppers.test.cc
test/celeritas/field/UserMapField.test.cc

- Include paths to kernel/rng have changed
- Missing CELER_FUNCTION on inline definition
- SB scaling answers are different by 1e-12
```
/ccs/home/s3j/.local/src/celeritas/test/celeritas/em/SeltzerBerger.test.cc:204: Failure
Values in: scaling_frac
Expected: expected_scaling_frac
2 of 16 elements differ
by 9.9999999999999998e-13 relative error or 1e-14 absolute error
i            EXPECTED       scaling_frac         Difference
7 2.1585790781929e-09 2.15857907820311e-09 4.73029576933669e-12
11     0.0041293798201 0.00412937982009147 -2.06601727778273e-12
```
I'm still seeing one failure in UrbanMsc @whokion :
```
/ccs/home/s3j/.local/src/celeritas/test/celeritas/em/UrbanMsc.test.cc:315: Failure
Values in: fstep
Expected: expected_fstep
1 of 8 elements differ
by 9.9999999999999998e-13 …
```

Fix HIP/Crusher build

---

src/celeritas/global/detail/AlongStepActionImpl.hh
src/celeritas/io/EventReader.cc
src/celeritas/phys/Primary.hh
src/celeritas/track/SimData.hh
src/celeritas/track/SimTrackView.hh
src/celeritas/track/detail/ProcessPrimariesLauncher.hh
src/celeritas/track/detail/ProcessSecondariesLauncher.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/ext/EventReader.test.cc
test/celeritas/global/Stepper.test.cc
test/celeritas/track/TrackInit.test.cc

This adds the elapsed time in the lab frame since the beginning of the event to the track state (see #357).
In the Geant4 PRM the time change over a step is defined as the ratio of the true step length to the harmonic mean of the pre- and post-step particle velocity, but in the code it seems to be calculated using only the pre-step velocity, which is how it's implemented here (maybe @whokion could check if this is correct?)
I also added a fix to make sure the number of steps is initialized to zero for primaries.

Add simulation time

---

src/corecel/Assert.hh

A global find-replace in #449 went awry and seems to break some build configurations.

Revert accidental change to Assert.hh

---

CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

This is for testing with SCALE building Celeritas inline as an `add_subdirectory`.
- Allows codes upstream to provide several external libraries without re-searching for them
- Prevents accidental C++11 building when an upstream code sets `CMAKE_CXX_STANDARD`.

Improve support for building as a "vendored" dependency

---

scripts/cmake-presets/wildstyle.json
scripts/docker/ci/run-ci.sh
src/celeritas/em/distribution/UrbanMscScatter.hh
src/celeritas/global/Stepper.hh
src/celeritas/global/detail/AlongStepActionImpl.hh
src/celeritas/phys/Interaction.hh
src/corecel/sys/KernelDiagnostics.cc
src/corecel/sys/KernelDiagnostics.hh
test/CMakeLists.txt
test/Test.cc
test/Test.hh
test/celeritas/TestEm3Base.cc
test/celeritas/TestEm3Base.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/global/DummyAction.hh
test/celeritas/global/Stepper.test.cc
test/celeritas/global/StepperTestBase.cc
test/celeritas/global/StepperTestBase.hh
test/detail/Macros.hh
test/detail/TestMain.cc

This now checks statistical/behavioral properties of the stepper loop, and adds a strict check that the results haven't changed when running on CI. I've also added two tests with MSC, which sometimes fail depending on the build configuration... it's failing when crossing a boundary:
```
{
pos = {
data_ = ([0] = -19.77, [1] = -0.42402311530894171, [2] = -0.08797186786456046)
}
dir = {
data_ = ([0] = 0.55080690811242594, [1] = -0.02079914375594025, [2] = -0.83437350484938677)
}
volume = (value_ = 3)
surface = {
id_ = (value_ = 12)
sense_ = outside
}
}
```

Refactor stepper test and add "action result" for MSC interaction

---

src/celeritas/io/EventReader.hh
src/celeritas/phys/Primary.hh
test/CMakeLists.txt
test/celeritas/TestEm3Base.cc
test/celeritas/TestEm3Base.hh
test/celeritas/global/AlongStep.test.cc
test/celeritas/global/AlongStepTestBase.cc
test/celeritas/global/AlongStepTestBase.hh
test/celeritas/global/StepperTestBase.cc
test/celeritas/global/StepperTestBase.hh

This test lets us probe the behavior of running multiple clones of a single primary input with a single "along-step" call: so we can examine the physics step change, geometry position change, etc. along the track.

Add granular along-step tests

---

app/demo-loop/LDemoIO.cc
app/demo-loop/LDemoIO.hh
app/demo-loop/demo-loop.cc
src/CMakeLists.txt
src/celeritas/phys/PrimaryGenerator.cc
src/celeritas/phys/PrimaryGenerator.hh
src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
src/celeritas/phys/PrimaryGeneratorOptionsIO.json.hh

This adds an optional demo loop input argument to generate primaries based on a specified quantity, particle type, energy, position, and direction rather than reading the events from a HepMC3 input file. For example, adding the following to the input JSON would generate the same primaries as in testem3.100k.hepmc3:
```json
"primary_gen_options": {"pdg": 11, "energy": 10000, "position": [-22, 0, 0], "direction": [1, 0, 0], "num_events": 100000, "primaries_per_event": 1}
```
This should make it easier to run with a range of inputs, e.g. for #460, without needing to create a new HepMC3 input file each time.

Optionally generate primaries without a HepMC3 input file in the demo loop

---

src/celeritas/em/distribution/UrbanMscHelper.hh
src/celeritas/em/distribution/UrbanMscScatter.hh
src/celeritas/em/distribution/UrbanMscStepLimit.hh
src/celeritas/phys/PhysicsData.hh
src/celeritas/phys/PhysicsStepUtils.hh
src/celeritas/phys/PhysicsTrackView.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/phys/PhysicsStepUtils.test.cc

This MR includes a consistent use of the energy loss range for each step:
- Calculate the energy loss range only once per step at `calc_physics_step_limit` and use the cache value elsewhere
- Add assessor and mutator functions for dedx_range in `PhysicsTrackView`
- Add a temporary tweak for numerical instability in the conversion from range  to step which will be replaced with `CELER_ASSERT(range > step)` later.

Cache the energy loss range as a physics state data

---

src/celeritas/phys/PhysicsTrackView.hh
test/celeritas/phys/Physics.test.cc

- Add additional tests for the range-to-step
- Don't evaluate the step calculation equation for small range $r$ (just above the cutoff $\rho$) but instead return $s = r$, since for $r = \rho + \epsilon$, the step equation simplifies to $s = \rho(1 + \epsilon) + O(\epsilon^2) \sim r$)

Add range-to-step tests and remove min

---

src/celeritas/ext/VecgeomParams.hh
src/celeritas/field/FieldPropagator.hh
src/orange/OrangeParams.hh
test/celeritas/field/FieldPropagator.test.cc

Based on the discussion we had today, it's possible to miss a tangent boundary if the intersection point is less than the chord tolerance. I've updated the test so that one track goes beyond the boundary by less than the chord tolerance (it barely ignores the surface) and the second by greater than the tolerance (it definitely hits it but at a grazing angle). Both tests now pass.
-----------
This is a work-in-progress commit where I'm narrowing down a potential failure in solving the intersection point with a single surface along a curved path with the field propagator. There are two slight variations on the same test in which the track barely leaves the current volume, traveling left at the point {0,5,0} along a curve of unit radius. The first variation starts the particle at $y=4 + 1.1 …

Fix field propagator at boundary crossings

---

app/CMakeLists.txt
src/CMakeLists.txt
src/corecel/Assert.hh
src/corecel/Macros.hh
src/corecel/cont/LabelIdMultiMap.hh
src/corecel/cont/Span.hh
src/orange/surf/detail/SurfaceAction.hh
test/celeritas/grid/PolyEvaluator.test.cc
test/celeritas/phys/Physics.test.cc
test/celeritas/phys/PhysicsStepUtils.test.cc
test/celeritas/random/curand/CurandPerformance.test.cu
test/corecel/OpaqueId.test.cc
test/corecel/sys/TypeDemangler.test.cc

Nvhpc was complaining about `break` being unreachable, and first (just in case the compiler macros were unexpected) I added a backport of [std::unreachable](https://en.cppreference.com/w/cpp/utility/unreachable).

NVHPC: silence warnings

---

CMakeLists.txt

Workaround for #442 to at least let people know what's going on until our VecGeom/RDC/CUDA coupling magic works.

Force disabling of shared libs for VecGeom 1.2.0+

---

src/celeritas/em/data/UrbanMscData.hh
src/celeritas/em/distribution/UrbanMscScatter.hh

This MR includes minor fixes for the UrbanMsc sampling:
- Fix the lowest kinetic energy to sample the multiple scattering (from 1e-3 eV to 1 eV)
- Return the original direction when the msc sampling is skipped (instead of {0,0,0})

Add minor fixes for UrbanMsc

---

src/celeritas/phys/PDGNumber.hh

The unintentional explicit constructor causes problems with nljson on clang 14 (ROCm 5.1.0). This somehow showed up because of the JSON I/O for PDG numbers introduced by #463.
```
FAILED: app/CMakeFiles/demo-loop.dir/demo-loop/demo-loop.cc.o
/opt/cray/pe/craype/2.7.15/bin/CC -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -I/ccs/home/s3j/.local/src/celeritas/src -I/ccs/home/s3j/.local/src/celeritas/build-ndebug/src -isystem /sw/crusher/spack-envs/base/opt/cray-sles15-zen3/gcc-11.2.0/nlohmann-json-3.10.2-fwiijvdxcf6lf7dfnojyswds4podhsem/include -isystem /opt/rocm-5.1.0/include -Wall -Wextra -pedantic -fdiagnostics-color=always -O3 -DNDEBUG -march=znver3 -mtune=znver3 -fopenmp -std=c++14 -MD -MT app/CMakeFiles/demo-loop.dir/demo-loop/demo-loop.cc.o -MF …
```

Fix clang-14/ROCM build with JSON enabled

---

CMakeLists.txt
app/CMakeLists.txt
app/geo-check/gcheck-four-levels.json
app/geo-check/gcheck-simplecms.json
src/CMakeLists.txt
test/CMakeLists.txt
test/celeritas/global/Stepper.test.cc

Thanks to @drbenmorgan and @mrguilima for helping constrain the passing/failing configurations, and @pcanal for finding out once and for all that it's the mix of linking `libcudart` and `libcudart_shared` that causes our linking errors.
At this draft state, linking against vecgeom 1.1.18 OR 1.2.0 (shared, cmake 3.23.1, CUDA 11.5) ends up with the main libraries linking against `libcudart`, but the final link steps (e.g., `CMakeFiles/demo-loop.dir/cmake_device_link.o` and `app/demo-loop`) use `libcudart_static`, and the code still crashes when running 1.2.0 presumably due to the indeterminate link order. *However*, when building CUDA without vecgeom, everything just links against `libcudart_static`.
When I set `CMAKE_CUDA_RUNTIME_LIBRARY=Shared` in the vecgeom builds now, though, nothing …

Better workaround for VecGeom 1.2 crashes

---

app/demo-rasterizer/RDemoRunner.cc
app/geo-check/GCheckKernel.cc
app/geo-check/GCheckRunner.cc
scripts/dev/celeritas-gen.py
src/celeritas/global/Stepper.cc
src/corecel/data/CollectionStateStore.hh
src/corecel/data/detail/CollectionImpl.hh
src/corecel/data/detail/Filler.device.t.hh
src/corecel/data/detail/Filler.hh
src/corecel/io/ScopedStreamFormat.hh
src/corecel/io/detail/ReprImpl.hh
test/celeritas/em/Fluctuation.test.cc
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/ext/Vecgeom.test.cc
test/celeritas/field/FieldPropagator.test.cc
test/celeritas/field/LinearPropagator.test.cc
test/celeritas/geo/GeoMaterial.test.cc
test/celeritas/global/AlongStepTestBase.cc
test/celeritas/mat/Material.test.cc
test/celeritas/phys/InteractorHostTestBase.cc
test/celeritas/phys/Particle.test.cc
test/celeritas/phys/Physics.test.cc
test/celeritas/phys/PhysicsStepUtils.test.cc
test/celeritas/random/RngEngine.test.cc
test/celeritas/random/XorwowRngEngine.test.cc
test/orange/Orange.test.cc
test/orange/OrangeGeoTestBase.cc

Pulled out of #494:
- Pass host data rather than a host-only high level "params" class into state store for easier testing
- Start using `celeritas::test` namespace for future tests
- Allow `Filler` class to be instantiated elsewhere
- Prevent vector-of-bools in collection since it can't be copied directly
- Move ScopedStreamFormat to its own file

Infrastructure changes for geo heuristic test

---

app/demo-loop/LDemoIO.cc
src/celeritas/em/distribution/UrbanMscScatter.hh
src/celeritas/global/alongstep/AlongStepUniformMscAction.hh

In #483 I started importing *all* the data from geant, including MSC data if it's on the file. When exporting ROOT data or just loading Celeritas data, it *is* always on the file: so MSC has accidentally been "always on" since that was merged.
The second error is fixing missing logic (and improving readability of similar logic)  in the MSC scatterer. When the geometry step was very small we did not set a "do not displace" flag. This allowed MSC to move the particle while it is on the boundary, leading to failures in the `is_on_boundary()` assertions incoming in #494.

Fix unintentional MSC enable and some displacement logic

---

src/celeritas/field/FieldDriverOptions.hh
src/celeritas/field/FieldPropagator.hh
src/celeritas/field/detail/FieldUtils.hh
test/celeritas/field/FieldPropagator.test.cc

With magnetic field enabled, occasionally an assertion in the along-step implementation would fail with an assertion that the physics step is greater than the boundary step. This ended up being because of the "substep end point is close enough to the boundary" condition in the field propagator: we counted the whole distance as being moved even though the substep end point may have been just a bit beyond the boundary point. My proposed solution reduces the "distance  traveled" based on the mismatch of the intercept and end-substep boundary points. The new field propagator unit tests show this in action.
In the above diagram, the endpoint _B_ is accepted because it's within the delta-intersection of the boundary crossing point. The geometry position at the end of the propagation is set to …

Fix unusual errors in field propagation

---

CMakeLists.txt
cmake/CeleritasLibrary.cmake

* Revert Force disabling of shared libs for newer vecgeom 
* Replace explicit link against CUDA::cudart with adding the proper path to the include directory.
* Inherit the CUDA_RUNTIME_LIBRARY setting from the library being used.

Improve static/shared CUDA library choice when linking VecGeom

---

src/celeritas/field/FieldDriver.hh
src/celeritas/field/FieldPropagator.hh
test/celeritas/field/FieldPropagator.test.cc

Previously, the `FieldPropagator` would not propagate tracks if the step length was smaller than the driver’s minimum step. This led to problems when a track starting on a boundary tried to take a very small step, but the geo state didn't actually change. Based on discussion with @sethrj, this changes the while loop in the `FieldPropagator` to a do...while loop to allow tracks taking small steps to advance.

Allow tracks taking small steps to propagate in field

---

src/celeritas/ext/VecgeomTrackView.hh
src/celeritas/field/FieldPropagator.hh
src/orange/OrangeTrackView.hh
test/celeritas/field/FieldPropagator.test.cc
test/orange/Orange.test.cc

The last remaining major failure mode in the regression suite is in simple CMS with fields, where ORANGE crashes (failure to find the new volume after a boundary crossing) and VecGeom hangs. @amandalund set up a minimal test case which is where an electron is traveling *mostly* inside the vacuum tube but *barely* scraping the inner cylinder every cycle. She tracked down the error to the fact that at the end of one step, the track is heading out of the inner vacuum into the tracker, but the first substep attempt in the next field propagator step changes the direction so it's reentrant: and `find_next_boundary` fails to check for that case.
We hit a similar problem in #501, but in that case the direction changed *before* calling `cross_boundary`.
Here's the plot of the three steps leading …

Fix failure when changing direction on boundary immediately after crossing

---

src/orange/OrangeTrackView.hh

If something goes awry while tracking with ORANGE, silently end the track's life rather than segfaulting when in release mode. Still fail with an assertion in debug though.

Escape rather than segfault on geometry error in release mode

---

src/celeritas/field/FieldPropagator.hh
src/orange/OrangeTrackView.hh
test/orange/Orange.test.cc

After #515 we were still seeing an assertion failure (`OrangeTrackView.hh:433: celeritas: internal assertion failed: init.volume`) with simple-cms+field using ORANGE, and the transport loop with VecGeom was taking ~15x more step iterations than ORANGE. This proposes a couple more fixes:
- Reset the boundary state after a reentrant boundary crossing so the next `find_next_step()` will be correct
- Make sure the boundary result from the `FieldPropagator` is accurate
Currently simple-cms+field with VecGeom will crash (`FieldPropagator.hh:239: celeritas: internal assertion failed: result.distance > 0 && result.distance <= step`) with `result.distance == 0`. This is because most of the time when a track changes direction on a boundary immediately after crossing, the field propagator just keeps …

Fix additional failures resulting from direction change on a boundary after crossing

---

src/celeritas/em/data/UrbanMscData.hh
src/celeritas/em/distribution/UrbanMscStepLimit.hh
src/celeritas/em/model/UrbanMscModel.cc
src/celeritas/global/alongstep/detail/UrbanMsc.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/global/Stepper.test.cc

The PR includes a bug fix for the minimum of the true path length limit which is now calculated every msc step and associated changes in along step and tests.   See comparisons between Geant4 and Celeritas for positrons after the bug fix with the testem3 benchmark with 100 events of a 10 GeV electron:

Fix the true path length limit of UrbanMsc

---

src/celeritas/ext/VecgeomTrackView.hh
src/celeritas/field/FieldDriver.hh
src/celeritas/field/FieldDriverOptions.hh
src/celeritas/field/FieldPropagator.hh
src/celeritas/global/CoreParams.cc
src/celeritas/global/CoreTrackData.hh
src/celeritas/global/CoreTrackView.hh
src/celeritas/global/alongstep/AlongStep.hh
src/celeritas/global/alongstep/detail/UrbanMsc.hh
src/celeritas/io/EventReader.nohepmc.cc
src/celeritas/phys/PhysicsParams.cc
src/corecel/io/StringUtils.cc
test/CMakeLists.txt
test/celeritas/field/FieldPropagator.test.cc
test/corecel/io/StringUtils.test.cc

VecGeom < 1.2 fails on this long step; on newer versions (and in ORANGE) it passes but takes ~78 equation evaluations per substep, which seems excessive for a uniform magnetic field. Credit to @amandalund for finding and adding a minimal test for the failure.
When the substep "nearly" hits the boundary, we were "accepting" the step by moving to the boundary, but I was unintentionally ignoring the momentum update from the substep. This situation is pretty uncommon and the momentum change usually small, so our tests didn't seem to catch anything from the change. (Perhaps with more boundary crossings we would eventually accumulate enough error?)
I've hardcoded a 128-substep-per-step limit into the field propagator. This also requires adding a new "implicit" action for whenever the geometry …

Fix field propagation for stuck and long-track particles

---

app/demo-loop/LDemoIO.cc
app/demo-loop/LDemoIO.hh
doc/api/celeritas.rst
doc/api/corecel.rst
src/celeritas/Constants.hh
src/celeritas/Quantities.hh
src/celeritas/Units.hh
test/celeritas/Constants.test.cc
test/celeritas/field/FieldPropagator.test.cc
test/celeritas/field/Fields.test.cc
test/celeritas/field/MagFieldEquation.test.cc
test/celeritas/global/Stepper.test.cc

Defining the Coulomb to have a magnitude of 1 in the Celeritas internal unit system was kind of arbitrary, and not very consistent with choosing cm/g instead of m/kg . Since `gauss` is the appropriate field strength unit for the [CGS-EMU system](https://en.wikipedia.org/wiki/Gauss_(unit)) we should probably use that instead. The updated unit system uses the gauss as a primary definition, and derives current/charge (A/C) from that.
Since users clearly expect tesla to be the field strength unit, change the LDemoIO input so that it is defined in units of Tesla regardless of the internal unit system.

Define gauss as internal field strength and use tesla for input

---

src/celeritas/em/data/UrbanMscData.hh
src/celeritas/em/distribution/UrbanMscScatter.hh
src/celeritas/em/distribution/UrbanMscStepLimit.hh
src/celeritas/global/alongstep/detail/UrbanMsc.hh
src/celeritas/phys/Interaction.hh
src/celeritas/phys/PhysicsData.hh
src/celeritas/phys/PhysicsTrackView.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/global/Stepper.test.cc

This MR intends to resolve remaining issues of multiple scattering and to verify physics results of multiple scattering including the total number of steps.
* Add MscRange (persistent properties within a volume) for multiple scattering to PhysicsTrackState and associated accessors to PhysicsTrackView
* Calculate MscRange in UrbanMscStepLimit at the first step in every tracking volume and reuse them at subsequent steps within the same volume
* Other related updates
See comparisons of MSC related distributions of positrons between celeritas (demo-loop) and Geant4 (g4app) with testem3-flat.gdml and 100 events of 10 GeV electrons:

Calculate range properties of multiple scattering at the first step in every tracking step  

---

src/celeritas/track/detail/ProcessSecondariesLauncher.hh

Since #527 the MSC step limiter checks if it's a track's first step by seeing if the MSC range properties stored in `PhysicsTrackView` have been cleared, but we neglected to reset the physics state in the case that a new track is initialized immediately in the parent's track slot.

Reset physics state when a secondary is initialized in the parent's track slot

---

scripts/cmake-presets/perlmutter.json
scripts/env/perlmutter.sh

I've added support for building Celeritas on Perlmutter with a few caveats:
- We need Spack  v0.18.0 and Perlmutter only has older version available so I have to use my own Spack installation for now.
- We need to install CUDA v1.7.0 in our Spack env. The CUDA version provided on Perlmutter is from NVHPC, which moved some headers file needed by Vecgeom. Another solution would be to tell Spack to keep `CPATH` set by the cudatoolkit module by setting `dirty: true` in the Spack config file; I don't like this option as much because it makes the build less reproducible depending on which modules are loaded...

Add CMakePresets and env script for perlmutter

---

app/demo-loop/demo-loop.cc
app/demo-rasterizer/demo-rasterizer.cc
src/corecel/sys/Device.cc
src/corecel/sys/Device.hh

Default size of CUDA heap is 8MB = 2^23 = 8388608, which is not enough to load cms-hllhc.gdml onto the GPU.  
A new heap size of 12MB = 12582912 works, as tested in demo-rasterizer.

Enable resizing of CUDA malloc heap to fix VecGeom failures

---

src/celeritas/CMakeLists.txt

ROOT's "use" file for CMake executes CMake `include_directories`, `link_directories` and `add_definitions` as well as appending to `CMAKE_CXX_FLAGS` among others. The primary issue here is the use of `include_directories`, which
- adds `-I` rather than `-isystem` paths to compile commands
- mixes these with project-local setttings (in Celeritas, the ROOT path appears _before_ anything else)
- flags appear in all subsequent compilations at the same directory scope any further subdirectories
This was observed to cause an issue at link time for Celeritas programs using `nlohmann_json`, where the found ROOT install was using a builtin `nlohmann_json` of different version to that found by CMake. The above scoped injection of the ROOT include path meant that different `nlohmann_json` headers …

Do not include ROOT's CMake "use" file to avoid potential nlohmann_json conflicts

---

doc/appendices/development.rst
src/celeritas/Types.hh
src/celeritas/user/StepCollector.cc
src/celeritas/user/StepCollector.hh
src/celeritas/user/StepData.hh
src/celeritas/user/StepInterface.hh
src/celeritas/user/detail/StepGatherLauncher.hh
src/corecel/data/CollectionBuilder.hh
test/CMakeLists.txt
test/celeritas/user/CaloTestBase.cc
test/celeritas/user/CaloTestBase.hh
test/celeritas/user/ExampleCalorimeters.cc
test/celeritas/user/ExampleCalorimeters.hh
test/celeritas/user/ExampleMctruth.cc
test/celeritas/user/ExampleMctruth.hh
test/celeritas/user/MctruthTestBase.cc
test/celeritas/user/MctruthTestBase.hh
test/celeritas/user/StepCollector.test.cc
test/celeritas/user/StepCollectorTestBase.cc
test/celeritas/user/StepCollectorTestBase.hh

This is the next step toward implementing #29 . It allows users to provide a volume name -> detector ID mapping that can be used to filter and map collected hit data.
Right now it's a little awkward because this makes the StepCollector have two different collection modes: one for mctruth-type collection, and another with detector filtering, and two StepInterface with the different modes can't be combined. I wonder if I should make two different Interface subclasses, one with filtering/mapping (detectors) and one without (mctruth), and add a "name" flag so they can instantiate different actions with the different data.

Add detector mapping and filtering to hit collector

---

scripts/dev/celeritas-gen.py

This should fix the odd behavior of duplicating components of the filename when run outside the `src/` and `test/` directories.

Fix celeritas-gen when run from root directory

---

src/corecel/math/Algorithms.hh
src/corecel/math/detail/AlgorithmsImpl.hh
src/orange/detail/UnitIndexer.hh
test/corecel/math/Algorithms.test.cc

This MR adds `upper_bound` functions to `corecel/math/Algorithms.hh`. The corresponding `lower_bound` functions were already present. The `orance/detail/UnitIndexer` is modified to use this implementation.

Add upper_bound functions to corecel/math

---

app/celer-dump-data.cc
app/celer-export-geant.cc
app/demo-loop/demo-loop.cc
scripts/dev/post-commit.git-clang-format
src/celeritas/ext/detail/GeantLoggerAdapter.cc
src/corecel/io/Logger.cc
src/corecel/sys/Device.cc
src/corecel/sys/Device.hh

On newer clang-format versions, the post-commit hook stopped working. (See https://github.com/llvm/llvm-project/issues/53220  and https://github.com/llvm/llvm-project/issues/54758 .) This fixes it! I've also moved a few code changes out of #567 .

Fix git-clang-format hook and code documentation

---

app/demo-loop/Transporter.cc
app/demo-loop/Transporter.hh
app/demo-loop/demo-loop.cc
src/celeritas/global/Stepper.cc
src/celeritas/global/Stepper.hh
src/celeritas/track/TrackInitUtils.hh
test/celeritas/global/AlongStepTestBase.cc
test/celeritas/global/Stepper.test.cc
test/celeritas/global/StepperTestBase.cc
test/celeritas/track/TrackInit.test.cc
test/celeritas/user/CaloTestBase.cc
test/celeritas/user/MctruthTestBase.cc
test/celeritas/user/StepCollector.test.cc

As some initial work toward #553, this PR changes the `operator()` methods in `Transporter` and `Stepper` to take `Span<const Primary>` instead of `std::vector<Primary>`. This will allow a transporter/stepper to operate on a subset of a larger vector of primaries (e.g., if they are divided over multiple threads).

Change Transport/Stepper interfaces to take span of `Primary` instead of vector

---

.jenkins

Specify `large_images` label which is used on nodes that can actually handle the Celeritas base image. The Celeritas builds were routinely causing some of the CI machines to run out of disk space.

Restrict where CUDA CI builds can run

---

src/accel/CMakeLists.txt
src/accel/EventAction.cc
src/accel/EventAction.hh
src/accel/InitializeActions.cc
src/accel/RunAction.cc
src/accel/RunAction.hh
src/accel/TrackingAction.cc
src/accel/TrackingAction.hh
src/accel/detail/LocalTransporter.cc
src/accel/detail/LocalTransporter.hh

Follow-up to #567: set up the shared Celeritas params and add a thread-local  transporter in the Acceleritas library.

Add thread-local transporter and Celeritas shared params setup to Acceleritas

---

app/CMakeLists.txt
app/demo-geant-integration/SensitiveDetector.cc
app/demo-geant-integration/SensitiveDetector.hh
app/demo-geant-integration/SensitiveHit.cc
app/demo-geant-integration/SensitiveHit.hh

Add a simple/example sensitive hit class for sensitive detectors:
- Assuming that the hit data structure is same for all sensitive detectors, which needs to be modified for different hit data structures for different sensitive detectors
- Merging hits is not implemented yet as the GPU transporter is not actually turned on

Add a simple SensitiveHit for demo-geant4-integration

---

app/demo-geant-integration/ActionInitialization.cc
app/demo-geant-integration/DetectorConstruction.cc
app/demo-geant-integration/EventAction.cc
app/demo-geant-integration/RunAction.cc
app/demo-geant-integration/TrackingAction.cc
src/accel/CMakeLists.txt
src/accel/ExceptionConverter.cc
src/accel/ExceptionConverter.hh
src/corecel/Assert.hh
src/corecel/Macros.hh
src/corecel/sys/MultiExceptionHandler.hh
test/CMakeLists.txt
test/accel/ExceptionConverter.test.cc

This is an attempt at a utility to convert Celeritas internal exceptions (runtime errors and debug failures) into Geant4-friendly `G4Exception` calls. Here's a debug failure on a single thread during tracking:
```
LocalTransporter.cc:128: info: Transporting 1 tracks with Celeritas
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : celer0004
issued by : /Users/seth/.local/src/celeritas/app/demo-geant-integration/SensitiveDetector.cc:52
precondition failed: collection_
*** Fatal Exception *** core dump ***
G4Track (0x11d81abd0) - track ID = 1, parent ID = 0
Particle type : e- - creator process : not available
Kinetic energy : 500 MeV - Momentum direction : (2.36658e-314,0,0)
Step length : 0 fm  - total energy deposit : 0 eV
Pre-step point : (0,0,0) - Physical …
```

Add Geant4 Exception converter

---

src/accel/CMakeLists.txt
src/accel/ExceptionConverter.cc
src/accel/ExceptionConverter.cu
src/accel/ExceptionConverter.hh

In the demo app I encountered `thrust::system_error` exceptions when running 128 threads, each with an absurd initializer storage requirement: thrust ran out of memory and crashed the program ungracefully. This PR catches thrust  exceptions, which requires a little extra work because including HIP thrust doesn't work unless using the HIP compilers: otherwise it assumes you are building CUDA thrust and have CUDA headers.
🎅🎄🎁

Convert Thrust exceptions to Geant4

---

app/demo-geant-integration/DetectorConstruction.cc
app/demo-geant-integration/GlobalSetup.cc
app/demo-geant-integration/GlobalSetup.hh
app/demo-geant-integration/MasterRunAction.cc
app/demo-geant-integration/RunAction.cc
src/accel/SetupOptions.hh
src/accel/SharedParams.cc
src/accel/SharedParams.hh
src/celeritas/CMakeLists.txt
src/celeritas/ext/GeantImporter.cc
src/celeritas/ext/GeantImporter.hh
src/celeritas/ext/VecgeomParams.cc
src/celeritas/ext/VecgeomParams.hh
src/celeritas/ext/detail/GeantGeoExporter.cc
src/celeritas/ext/detail/GeantGeoExporter.hh
src/orange/OrangeParams.cc
src/orange/OrangeParams.hh
test/celeritas/GeantTestBase.cc
test/celeritas/GeantTestBase.hh
test/celeritas/GlobalGeoTestBase.cc
test/celeritas/GlobalGeoTestBase.hh
test/celeritas/OnlyGeoTestBase.hh
test/celeritas/data/solids.gdml
test/celeritas/ext/Vecgeom.test.cc
test/celeritas/field/FieldPropagator.test.cc
test/celeritas/field/LinearPropagator.test.cc
test/celeritas/geo/GeoMaterial.test.cc
test/celeritas/geo/HeuristicGeoTestBase.hh

This is a stopgap measure before #557 . It adds a helper class to export the Geant4 geometry from a "world" volume as a GDML, and adapts the interface from #557 along with the unit test harness updates I made. The new test geometry `solids.gdml` (from Geant4) is chock full of errors, though, so it's not a very useful test except to show that the results will change when Guilherme's work is finished.
Because G4's GDML exporter simply exits if it's not the master thread, we have to ensure that the `SharedParams` initialization happens on the master thread, so that logic has changed.
Furthermore, to allow us to test the integration on HIP and/or with ORANGE, I've added a superficial G4 constructor and added some hacky code to propagate the GDML file into the `accel` helper functions.
--- …

Auto-export GDML from Geant4 geometry

---

README.md
scripts/spack.yaml
src/corecel/cont/Label.cc
test/celeritas/ext/Vecgeom.test.cc

I think this should address two recent issues @amandalund saw with Geant4 10.7 (exported GDML pointer suffixes) and VecGeom 1.1.17 (crash on VGDML read with unsupported shapes). I also documented that we're only testing Geant4 11.0 and VecGeom 1.2 but that other versions may work (and we want to support them if it doesn't break things).

Minor fixes for older Geant4/VecGeom releases

---

app/CMakeLists.txt
app/demo-geant-integration/GlobalSetup.cc
app/demo-geant-integration/GlobalSetup.hh
app/demo-geant-integration/MasterRunAction.cc
app/demo-geant-integration/NoFieldAlongStepFactory.cc
app/demo-geant-integration/NoFieldAlongStepFactory.hh
src/accel/AlongStepFactory.hh
src/accel/SetupOptions.hh
src/accel/SharedParams.cc

This defines a factory interface for Acceleritas users to create an along-step action. We'll still probably want to enhance the demo by including a parameterized CMS field.

Support user-defined along-step kernels in accel+demo

---

src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc

These options changed in #514 . This lets old inputs for the `demo-loop` to continue to work and makes it more concise in the not uncommon case where the input is simpler.

Add backward compatibility for primary generators

---

src/celeritas/io/RootStepWriter.cc

Running some problems with ROOT MC truth output enabled results in a failure:
```
/home/alund/celeritas_project/celeritas/app/demo-loop/demo-loop.cc:254: critical: While running input at testem3.inp.json: /home/alund/celeritas_project/celeritas/src/corecel/OpaqueId.hh:60:
celeritas: precondition failed: *this
```
because the post-step volume ID will be invalid if the track is outside. This simply allows invalid volume IDs to be stored in the steps TTree.

Allow invalid volume IDs in ROOT MC truth output

---

test/CMakeLists.txt

Very minor fix to one test which was failing when the `G4ENSDFSTATEDATA` variable wasn't set directly in the environment. Following other tests, fixed by adding the optional Geant4 env to the offending test. Credit should go to Chris Brady at Warwick for identifying this!

Add Geant4 environment to celeritas/ext/VecGeom

---

src/celeritas/CMakeLists.txt
src/celeritas/em/data/UrbanMscData.hh
src/celeritas/em/distribution/UrbanMscHelper.hh
src/celeritas/em/distribution/UrbanMscScatter.hh
src/celeritas/em/distribution/UrbanMscStepLimit.hh
src/celeritas/em/model/UrbanMscModel.cc
src/celeritas/em/model/UrbanMscModel.hh
src/celeritas/em/process/MultipleScatteringProcess.cc
src/celeritas/global/alongstep/detail/UrbanMsc.hh
src/celeritas/grid/ValueGridData.cc
src/celeritas/grid/ValueGridData.hh
src/celeritas/io/ImportProcess.hh
src/celeritas/mat/MaterialData.hh
src/celeritas/mat/MaterialParams.cc
src/celeritas/mat/MaterialView.hh
src/celeritas/phys/ImportedProcessAdapter.cc
src/celeritas/phys/ImportedProcessAdapter.hh
src/celeritas/phys/PhysicsData.hh
src/celeritas/phys/PhysicsParams.cc
src/celeritas/phys/PhysicsTrackView.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/mat/Material.test.cc
test/celeritas/phys/Physics.test.cc
test/celeritas/phys/ProcessBuilder.test.cc

This is a follow-on from work done in #457 with the goal of physics class (builders, etc.) for #253 . It removes the MSC process from physics processing and puts particle- and material-dependent MSC data in the UrbanMsc class itself.
Since now the only purpose of passing the MscProcess into the physics is to construct the model that gets looked up by the `AlongStepUniformMscAction`, we'll want a follow-on PR to remove the MSC "process" and Urban "model" entirely since these aren't treated the same way as all the other discrete and along-step processes in the code. At that point we can add the high-energy MSC model and consider how to simplify and combine the different along-step actions.

Remove MSC data from core physics class

---

scripts/cmake-presets/crusher.json
scripts/env/crusher.sh

For the latest benchmark runs I've redone the crusher toolchain to use LLVM for the C++ compilers in *addition* to for the HIP compiler.

Update crusher environment to use AMD LLVM compilers

---

cmake/FindGeant4.cmake

If Geant4 is installed with only static libraries, the `FindGeant4` wrapper will fail as it directly sets properties on the unavailable `Geant4::G4global` shared target. This was identified during tests with static Geant4+VecGeom+CUDA builds which experiments may be using.
Check that the shared `Geant4::G4global` target exists before setting its properties. Fallback to the static target if the shared does not exist. This is safe against dual installs, as Geant4 will prefer shared targets in this case.
Only tested on Linux with the celeritas spack environment configured with GCC11.2/CUDA11.7, and everything except Geant4 installed. VecGeom 1.2.1 was installed using the `~shared` variant to set up the static build of that. Geant4 was then built manually against this in static or shared …

Support linking to Geant4 static libraries

---

src/celeritas/Types.cc
src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
src/celeritas/io/ImportPhysicsTable.cc
src/celeritas/io/ImportProcess.cc
src/celeritas/phys/PrimaryGeneratorOptions.hh
src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc
src/corecel/io/EnumStringMapper.hh
src/corecel/io/OutputInterface.cc
src/corecel/io/StringEnumMapper.hh
src/orange/OrangeTypes.cc
src/orange/construct/OrangeInputIO.json.cc
test/CMakeLists.txt
test/corecel/cont/Range.test.cc
test/corecel/io/EnumStringMapper.test.cc
test/corecel/io/StringEnumMapper.test.cc

This defines a small helper class to improve the safety of enum->string mapping and reduce the amount of code we have to use to do it.

Add enum string mapper

---

src/celeritas/field/FieldPropagator.hh
src/celeritas/field/detail/FieldUtils.hh
test/celeritas/field/FieldPropagator.test.cc

See #618 for a description of the problem. If the chord is super small, the starting direction (which is kept in sync with the field state momentum) will be very close to the expected chord direction. This holds even when the chord length is zero. Therefore *only* update the trial direction for nontrivial (i.e. greater than the driver's "minimum step") distances.
Fixes #618

Fix NaN/assertion when taking extremely small steps in a field

---

src/orange/surf/CylCentered.hh
test/orange/surf/CylCentered.test.cc

The cylinder intersection method only returned an "infinite" distance if the direction was exactly zero rather than a very small number, leading to numerical errors in the intersection point. I also tried fixing by removing the assertion (letting small `a` propagate through the solver) and by clamping `a` to `QuadraticSolver::min_a()`, but using this tolerance resulted in the most correct distances.
Closes #621

Fix ORANGE intersection along cylinder axis

---

app/demo-loop/LDemoIO.cc
src/accel/SharedParams.cc
src/celeritas/ext/GeantPhysicsOptions.hh
src/celeritas/phys/ProcessBuilder.cc
src/celeritas/phys/ProcessBuilder.hh
test/CMakeLists.txt
test/celeritas/GeantTestBase.cc
test/celeritas/GeantTestBase.hh
test/celeritas/GlobalGeoTestBase.cc
test/celeritas/GlobalGeoTestBase.hh
test/celeritas/ImportedDataTestBase.cc
test/celeritas/ImportedDataTestBase.hh
test/celeritas/RootTestBase.cc
test/celeritas/RootTestBase.hh
test/celeritas/TestEm15Base.hh
test/celeritas/TestEm3Base.hh
test/celeritas/em/UrbanMsc.test.cc
test/celeritas/ext/RootImporter.test.cc
test/celeritas/ext/Vecgeom.test.cc
test/celeritas/geo/GeoMaterial.test.cc
test/celeritas/global/AlongStep.test.cc
test/celeritas/global/Stepper.test.cc
test/celeritas/user/StepCollector.test.cc

This cleans up some of the "pre-ProcessBuilder" code in the Geant4 test harness so that we now use GeantPhysicsOptions to set up the actual imported data and physics options. The process builder is also used for setting up physics loaded from ROOT files, so we can reuse that data in the UrbanMSC and GeoMaterial tests. While cleaning up the UrbanMSC test I identified and fixed some copy-paste errors and did some simplification.
To avoid changing test results, the Geant4 process construction reorders the input processes to match what used to be there: the next time we rebaseline the tests, we can remove that extra complexity.

Use ProcessBuilder for ROOT and Geant4 tests

---

src/celeritas/em/data/UrbanMscData.hh
src/celeritas/em/msc/UrbanMscScatter.hh
src/celeritas/em/msc/UrbanMscStepLimit.hh
src/celeritas/phys/Interaction.hh
test/celeritas/global/AlongStep.test.cc

Because of a discontinuity in the Urban MSC positron cross section at 10 MeV, when a positron has energy slightly larger than 10 MeV it's possible for the final transport mean free path to be _larger_ than the initial mfp and therefore for the `alpha` calculated in `UrbanMscStepLimit::calc_geom_path()` to be negative. Since `UrbanMscScatter::calc_true_path()` checked for `alpha < 0` (instead of `alpha == -1`, indicating a small true path length) when determining which geom path --> true path conversion to use, the true path for these positrons was calculated using the wrong transformation.
See full discussion in #615
Some overlap with #641 ;)
Closes #615

Fix incorrect Urban MSC path length correction due to discontinuity in positron cross section

---

app/celer-export-geant.cc
src/celeritas/ext/GeantPhysicsOptions.hh
src/celeritas/ext/GeantPhysicsOptionsIO.json.cc
src/celeritas/ext/detail/GeantPhysicsList.cc
test/CMakeLists.txt
test/celeritas/GeantTestBase.cc
test/celeritas/ext/GeantImporter.test.cc

This fixes https://github.com/celeritas-project/celeritas/pull/642#discussion_r1104505415 and turns off the Geant4 physics list diagnostic output (which is shown at the 'diagnostic' level by default).

Activate fine-grid MSC test and make GeantImporter less verbose

---

src/celeritas/global/alongstep/AlongStep.hh
test/CMakeLists.txt
test/celeritas/MockTestBase.cc
test/celeritas/MockTestBase.hh
test/celeritas/global/AlongStep.test.cc
test/celeritas/phys/Physics.test.cc

For very small energies the calculated speed of a non-stopped particle can be exactly zero: see the note on `celeritas::ParticleTrackView::beta_sq()`. This only occurs when the `energy / mass` ratio is less than numeric epsilon (so ~1e-17 MeV for electrons). Rather than try to improve the precision of `beta_sq` for massive particles that are nearly at rest (not relevant to the current HEP detectors we're targeting), I've just added a conditional to *not* adjust the global time when the speed is almost zero.
Fixes #616

Check for unlikely "zero speed" condition

---

app/CMakeLists.txt
app/demo-geant-integration/HitClassesLinkDef.h

Also disable clang-format on content of HitClassesLinkDef.h

Disable rootmap file for demo-geant-integration dictionary.

---

app/demo-geant-integration/EventAction.cc
scripts/cmake-presets/goldfinger.json
src/accel/HepMC3PrimaryGenerator.cc
src/accel/LocalTransporter.cc
src/accel/detail/HitManager.cc
src/accel/detail/HitProcessor.cc
src/accel/detail/HitProcessor.hh
src/celeritas/ext/GeantImporter.cc
src/celeritas/geo/GeoMaterialParams.cc
src/celeritas/io/ImportVolume.hh
test/CMakeLists.txt
test/accel/detail/HitProcessor.test.cc
test/celeritas/SimpleCmsTestBase.hh

Trying to run https://github.com/sethrj/hgcal-prototype, I identified a few issues:
- We assumed logical volumes in the Geant4 geometry had contiguous `InstanceID`s. This is not the case; so I had to modify the `GeantImporter` and `GeoMaterialParams` to fix.
- To stop long-running tracks without killing the entire simulation I added signal handling to the Celeritas transporter in the `accel` framework.
- *Many* hits in the Celeritas SD callback were mapping to incorrect volumes. I added code to try bumping particles across boundaries based on the particle's direction. It's possible we will never be able to get rid of this due to minor differences in volume locations between VecGeom and Geant4 geometry representations.
With this fix in place, we now get helpful error messages describing …

Fix volume mapping and navigation issues found with HGCal prototype

---

interface/celeritas.i
scripts/docker/dev/centos7-rocm5.yaml
scripts/docker/dev/jammy-cuda11.yaml
scripts/spack.yaml

This has probably been broken since #634 . I did not add SWIG wrapper instantiations for `ImportModel` or `ImportMscModel`.
This fixes those omissions as well as updating the Spack environment script to require SWIG 4.1 (which is the first version that can handle C++14-style `[[attributes]]`).

Fix SWIG and update requirements

---

CMakePresets.json
scripts/cmake-presets/goldfinger.json
scripts/cmake-presets/wildstyle.json
src/celeritas/field/FieldDriver.hh
src/celeritas/field/FieldDriverOptions.hh
src/celeritas/field/FieldPropagator.hh
src/celeritas/field/detail/FieldUtils.hh
test/celeritas/field/FieldPropagator.test.cc

While debugging the coincident range + boundary problem we discovered after removing the fixup in #650, I discovered that the "miss distance" calculation (responsible for reducing the reported distance to the boundary) 
There was a missing `sqrt` because of a badly chosen function name, so that the distance being subtracted off was microscopic (1e-13 instead of 1e-7) and ignored due to roundoff.
Looking again in more detail it's clear that we were hitting many coincident boundaries + physics step because the field propagator "snaps" steps to the boundary if the intersection point is close. I have updated the field propagator so that we accept a trial boundary only if (1) the intersection point is *closer* than the substep endpoint, in which case the resulting distance is guaranteed less …

Fix coincident boundary/step created by field propagator

---

test/celeritas/global/AlongStep.test.cc
test/celeritas/global/AlongStepTestBase.cc
test/celeritas/global/AlongStepTestBase.hh

- A low energy (~2 keV) electron near a boundary has a physics step limited by range (range = 6.41578930992857482e-06)
- `UrbanMscStepLimit` calculates the geometrical path using the range as the true path (geom path = 6.11329043405346748e-07)
- Since the track is very near the boundary, the field propagator moves the track to the boundary but just sets the distance equal to the step (the geom path)
- Since the geom path is unchanged, the true path calculated in the g --> t transformation in `UrbanMscScatter` is equal to the range
- The track loses all energy over the step but is on a boundary

Add minimal failing test for #620

---

src/celeritas/field/FieldDriver.hh
src/corecel/io/Repr.hh
test/CMakeLists.txt
test/TestMacros.test.cc
test/celeritas/field/DiagnosticStepper.hh
test/celeritas/field/FieldDriver.test.cc
test/testdetail/TestMacrosImpl.hh

This demonstrates that #619 will be fixed by properly killing particles less than ~1 keV. The number of equation evaluations required to meet the FieldDriver 'accurate' tolerance increases rapidly with decreasing energy below 1 keV for electrons. At 1 MeV, ~10 steps are required to converge on a ~0.4cm step from a 10cm physics length. At 1 eV, ~250 are required for a 0.08cm step. So if we have low energy tracks in a low density material we're really screwed.

Characterize and remove field driver convergence assertions

---

src/celeritas/global/alongstep/detail/FluctELoss.hh
src/celeritas/global/alongstep/detail/MeanELoss.hh
src/celeritas/phys/PhysicsData.hh
src/celeritas/phys/PhysicsStepUtils.hh
src/corecel/math/Quantity.hh
test/corecel/math/Quantity.test.cc

This defines a few operators for Quantity that don't change the underlying units. It also fixes an error if the underlying quantity and unit types are integers (not used presently in the code but could be useful for a memory diagnostic like KB/MB).

Add math operators to Quantity

---

src/celeritas/ext/GeantSetup.cc
src/celeritas/ext/ScopedRootErrorHandler.cc
test/CMakeLists.txt

When loading ROOT, or when activating the Geant4 run managers, the two codes register signal callback functions for lots of "unexpected" system interrupts like SIGILL (illegal instruction), SIGKILL (which shouldn't even be interceptable), and SIGSEGV. This strikes me as being both unexpected (the scope of the interrupt override exceeds that of the run manager or ROOT actions) and dangerous (hitting an illegal instruction or segmentation violation puts the code in an unusable state). It might also be interfering with debugging... I was getting unexpected `SIGILL` just from constructing a `std::logic_error`, and then Geant4 and ROOT tried to intercept them.
Unless we're running through an external user's Geant4 app, disable these signal handlers.
There is also a fix for a test introduced in …

Disable Geant4+ROOT system signal hooks

---

CMakePresets.json
scripts/cmake-presets/perlmutter.json
scripts/cmake-presets/summit.json

I unintentionally broke the CMake presets on summit when I added `.reldeb` to the top level `CMakePresets.json` in #654.

Fix duplicate CMake presets

---

src/celeritas/global/KernelContextException.cc
test/celeritas/global/KernelContextException.test.cc

Closes #640 . Should fix CI in #607 .

Only capture kernel context if corresponding track is alive

---

app/celer-dump-data.cc
src/accel/SharedParams.cc
src/accel/detail/HitProcessor.cc
src/accel/detail/HitProcessor.hh
src/celeritas/CMakeLists.txt
src/celeritas/ext/GeantImporter.cc
src/celeritas/ext/GeantImporter.hh
src/celeritas/ext/detail/GeantVolumeVisitor.cc
src/celeritas/ext/detail/GeantVolumeVisitor.hh
src/celeritas/global/Stepper.cc
src/celeritas/track/TrackInitParams.hh
test/CMakeLists.txt
test/celeritas/GeantTestBase.cc
test/celeritas/GeantTestBase.hh
test/celeritas/ext/GeantImporter.test.cc

TileCal's GDML file has duplicate volume names (and colons in the name) which are stripped when reading (and the colons replaced by underscores when writing). This leads to duplicate `ImportVolume` names that can't be resolved to unique VecGeom volumes. I added an option to the GeantImporter to convert the in-memory logical volume names to their GDML equivalents, so that they will match the exported GDML names. This option should be used whenever the client loads the geometry themselves, *not* when Celeritas loads the GDML file.
The TileCal example also accessed the `GetTrack()` property of the step, which resulted in a null pointer dereference: this has been fixed by allocating a local track that simply has no extra data.
As a debugging feature, we also now export a ROOT file with the …

Fix Geant4/GDML volume names to get TileCal working

---

app/demo-geant-integration/demo-geant-integration.cc
example/accel/accel.cc
src/accel/SharedParams.cc
src/celeritas/ext/GeantImporter.cc
src/celeritas/ext/GeantImporter.hh

When putting in the Geant4 importer I added some very coarse granularity (em vs hadron) for importing particles and processes. Because we don't distinguish between EM particles we support (e/gamma) and those we don't (muon) we end up having to manually ignore mubrems, muioni, etc. This PR makes the `accel` code ignore `muioni` and such by default (and correspondingly write out less data).

Ignore Geant4 muons and muon processes by default in accel

---

src/accel/detail/HitManager.cc
src/celeritas/phys/ImportedModelAdapter.cc

When we elect *not* to strip pointers from a GDML file, and we want touchable locations in the SD callbacks, the HitMapper construction fails because the pointers are effectively added twice (so the first pointer is parsed as being part of the "name" of the label whereas the second pointer becomes the extension).
Also adds an always-on assertion for checking imported models to avoid a segfault if the model failed to import.

Fix hit mapping when using GDML geometry with pointers

---

src/corecel/data/Collection.hh
src/corecel/data/detail/CollectionImpl.hh
src/orange/OrangeData.hh
src/orange/OrangeTrackView.hh
src/orange/Types.hh
src/orange/construct/OrangeInput.hh
src/orange/construct/OrangeInputIO.json.cc
src/orange/construct/SurfaceInputBuilder.cc
src/orange/construct/SurfaceInputBuilder.hh
src/orange/detail/LevelStateAccessor.hh
src/orange/detail/UnitIndexer.hh
src/orange/detail/UnitInserter.cc
src/orange/surf/Surfaces.hh
src/orange/surf/detail/SurfaceAction.hh
src/orange/univ/SimpleUnitTracker.hh
src/orange/univ/VolumeView.hh
src/orange/univ/detail/Types.hh
src/orange/univ/detail/Utils.hh
test/corecel/data/Collection.test.cc
test/orange/OrangeGeoTestBase.cc
test/orange/OrangeGeoTestBase.hh
test/orange/detail/UnitIndexer.test.cc
test/orange/surf/SurfaceAction.test.cc
test/orange/surf/SurfaceAction.test.hh
test/orange/univ/SimpleUnitTracker.test.cc
test/orange/univ/VolumeView.test.cc
test/orange/univ/detail/SenseCalculator.test.cc
test/orange/univ/detail/SurfaceFunctors.test.cc

In this PR, ORANGE is modified such that separate local and global types are used for volume and surface ids. To facilitate this, an `ItemMap<T1, T2>` class is added in order to access globally-typed `Collections` with locally-typed indices.

Differentiate between local and global Volume and Surface Ids within ORANGE

---

.jenkins
scripts/cmake-presets/wildstyle.json
scripts/docker/build.sh
scripts/docker/ci/Dockerfile
scripts/docker/dev/Dockerfile
test/celeritas/GeantTestBase.cc
test/celeritas/ext/Vecgeom.test.cc

This updates the CI version of VecGeom to 1.2.2. Required for #557.

Update CI VecGeom to 1.2.2

---

src/celeritas/ext/detail/GeantModelImporter.cc
test/CMakeLists.txt
test/celeritas/OneSteelSphereBase.hh
test/celeritas/data/one-steel-sphere.gdml
test/celeritas/data/one-steel-sphere.org.json
test/celeritas/data/one-steel-sphere.org.omn
test/celeritas/ext/GeantImporter.test.cc
test/celeritas/global/Stepper.test.cc

It’s possible for the lower energy bound of the microscopic cross section grid to be higher than the upper bound if the production cut values are very high. Simply skip building the grid if this is the case instead of requiring `min_energy < max_energy`.

Fix imported micro xs when lower energy grid bound is higher than upper bound
