.gitignore, scripts/dev/celeritas-gen.py, src/CMakeLists.txt, src/base/Algorithms.hh, src/base/ArrayIO.hh, src/base/ArrayUtils.hh, src/base/ArrayUtils.i.hh, src/base/Atomics.hh, src/base/ColorUtils.cc, src/base/DeviceAllocation.cuda.cc, src/base/DeviceAllocation.hh, src/base/DeviceVector.hh, src/base/DeviceVector.i.hh, src/base/Memory.cu, src/base/Memory.hh, src/base/Memory.i.hh, src/base/Memory.nocuda.cc, src/base/SpanIO.hh, src/base/StackAllocatorStore.cc, src/base/detail/InitializedValue.hh, src/comm/Communicator.nompi.cc, src/comm/ScopedMpiInit.nompi.cc, test/base/ArrayUtils.test.cc, test/base/DeviceAllocation.test.cc, test/base/DeviceVector.test.cc
This PR is to keep the physics track/interactor one cleaner.
=> Minor infrastructure fixes

CMakeLists.txt, app/CMakeLists.txt, app/demo-rasterizer/ImageIO.cc, app/demo-rasterizer/ImageIO.hh, app/demo-rasterizer/ImagePointers.hh, app/demo-rasterizer/ImageStore.cc, app/demo-rasterizer/ImageStore.hh, app/demo-rasterizer/ImageTrackView.hh, app/demo-rasterizer/ImageTrackView.i.hh, app/demo-rasterizer/RDemoKernel.cu, app/demo-rasterizer/RDemoKernel.hh, app/demo-rasterizer/RDemoRunner.cc, app/demo-rasterizer/RDemoRunner.hh, app/demo-rasterizer/demo-rasterizer.cc, app/demo-rasterizer/simple-driver.py, scripts/build/emmet.cmake, src/base/Assert.hh, src/base/ColorUtils.cc, src/base/DeviceVector.hh, src/geometry/GeoParams.cc, src/geometry/GeoParams.hh, src/geometry/GeoParamsPointers.hh, test/geometry/data/lariat.gdml, test/geometry/data/slabsGeometry.gdml
This version is a little hacky:
- Uses JSON + raw binary output instead of something sensible
- Rendering the image only easy with "export controlled" software (supplementary code in SCALE that I plan to release as a standalone package but for now is private to me/tom/stefano)
=> Add geometry raytrace test app

app/demo-interactor/simple-driver.py, app/demo-rasterizer/RDemoKernel.cu, app/demo-rasterizer/RDemoRunner.cc, app/demo-rasterizer/simple-driver.py, scripts/build/lq-cuda.cmake, scripts/build/lq-cuda.sh, scripts/build/lq.cmake, scripts/build/lq.sh, src/base/ArrayUtils.hh, src/base/ArrayUtils.i.hh, src/geometry/GeoStatePointers.hh, src/geometry/GeoStateStore.cc, src/geometry/GeoStateStore.hh, src/geometry/GeoTrackView.hh, src/geometry/GeoTrackView.i.hh, src/geometry/LinearPropagator.hh, src/geometry/LinearPropagator.i.hh, src/geometry/Types.hh, test/CMakeLists.txt, test/geometry/LinearPropagator.test.cc, test/geometry/LinearPropagator.test.cu, test/geometry/LinearPropagator.test.hh
New class geometry/LinearPropagationHandler, uses VecGeom navigation to propagate tracks along straight lines to the next volume boundary.
The CPU version currently passes  all tests.
The CUDA version builds and runs, but  currently  some consistency checks.  To be investigated.
=> Implement linear propagation

.gitattributes, app/geant-exporter/data/two-boxes.gdml, test/CMakeLists.txt, test/geometry/data/lariat.gdml, test/geometry/data/slabsGeometry.gdml, test/geometry/data/twoBoxes.gdml, test/io/data/geant-exporter-data.root
- Remove large CMS ROOT file until @stognini replaces with smaller one (disabling test as well)
- Remove unused large GDML file
- Convert other GDML files into regular git storage
=> De-LFS files

src/physics/base/Interaction.hh, src/physics/em/EPlusGGInteractor.hh, src/physics/em/EPlusGGInteractor.i.hh, src/physics/em/EPlusGGInteractorPointers.hh, test/physics/em/EPlusGGInteractor.test.cc
Not sure whether clang-format is applied correctly.  Can you check?  Thanks.
=> Implement EPlusGGInteractor

src/base/Algorithms.hh, src/physics/em/BetheHeitlerInteractor.hh, src/physics/em/BetheHeitlerInteractor.i.hh, src/physics/em/BetheHeitlerInteractorPointers.hh, test/CMakeLists.txt, test/physics/em/BetheHeitlerInteractor.test.cc
This commit brings in the following new files:
- src/physics/em/BetheHeitlerInteractor.hh
- src/physics/em/BetheHeitlerInteractor.i.hh
- src/physics/em/BetheHeitlerInteractorPointers.hh
- test/physics/em/BetheHeitlerInteractor.test.cc
and updates test/CMakeLists.txt to include the test.
=> Add BetheHeitlerInteractor

test/io/RootImporter.test.cc
#include <algorithm> into test/io/RootImporter.test.cc
=> gcc 8.3.0 error: find_if is not a member of std

src/CMakeLists.txt, src/physics/em/BetheHeitlerModel.cc, src/physics/em/BetheHeitlerModel.hh, src/physics/em/GammaAnnihilationProcess.cc, src/physics/em/GammaAnnihilationProcess.hh, src/physics/em/detail/BetheHeitler.cu, src/physics/em/detail/BetheHeitler.hh, src/physics/em/detail/BetheHeitlerInteractor.hh, src/physics/em/detail/BetheHeitlerInteractor.i.hh, test/CMakeLists.txt, test/physics/InteractorHostTestBase.cc, test/physics/InteractorHostTestBase.hh, test/physics/em/BetheHeitler.test.cc
* Move BetheHeitlerInteractor header and impl to em/detail
* BetheHeitlerInteractorPointers -> detail/BetheHeitler
* `BetheHeitlerInteractor.test.cc` -> `BetheHeitler.test.cc`
* Added BetheHeitlerModel (host and device code)
* Split `check_conservation` into separate energy and
momentum conservation checks
* Added energy conservation check to test
* Added to test the RNG invocation counter and
`SCOPED_TRACE` for incident energies
=> Add BetheHeitlerModel and GammaAnnihilationProcess

CMakeLists.txt, interface/CMakeLists.txt, interface/celeritas.i, scripts/build/yuri.cmake, scripts/build/yuri.sh, scripts/dev/celeritas-gen.py, scripts/dev/env/celeritas-darwin.yaml, scripts/dev/env/celeritas-linux.yaml, scripts/docker/env.yaml
Adds a few initial components for SWIG interfaces to celeritas for debugging, data exploration, etc. See https://github.com/celeritas-project/celeritas-docs/blob/master/nb/physics/data.ipynb.
=> Add SWIG interface

app/demo-interactor/HostKNDemoRunner.cc, app/demo-interactor/HostKNDemoRunner.hh, src/base/Algorithms.hh, src/base/PieStateStore.hh, src/physics/grid/GridIdFinder.hh, src/physics/grid/GridIdFinder.i.hh, test/CMakeLists.txt, test/base/Algorithms.test.cc, test/physics/InteractorHostTestBase.cc, test/physics/InteractorHostTestBase.hh, test/physics/base/Particle.test.cc, test/physics/grid/GridIdFinder.test.cc, test/physics/material/Material.test.cc
These are necessary for #141 .
=> Add PieStateStore and GridIdFinder helper classes

app/demo-rasterizer/RDemoKernel.cu, src/geometry/GeoTrackView.hh, src/geometry/LinearPropagator.i.hh, test/geometry/GeoParams.test.cc, test/geometry/GeoParamsTest.hh, test/geometry/GeoTrackView.test.cc, test/geometry/LinearPropagator.test.cc, test/geometry/LinearPropagator.test.cu, test/geometry/data/fourLevels.gdml
A new four-levels-deep geometry model is added.
More complex testing can be done on this geometry model.
=> Add fourLevels geometry model, and modify basic geom tests accordingly.

doc/CMakeLists.txt, scripts/docker/dev/bionic-minimal.yaml, scripts/docker/dev/focal-cuda11.yaml, src/base/Assert.hh, src/comm/ScopedMpiInit.cc, src/physics/em/EPlusGGMacroXsCalculator.i.hh, src/physics/em/detail/BetheHeitlerInteractor.hh, src/physics/em/detail/LivermorePE.hh, src/physics/grid/RangeCalculator.hh
Build documentation for `detail`  classes while in debug mode, and fix a couple of  errors/warnings in the docs.
=> Fix documentation

test/physics/em/MollerBhabha.test.cc
I started doing this as part of the "interaction always gets a secondary" refactor but left it on my branch and only remembered when I saw the new test for #194 ☹️ These changes should make additional tests simpler and easier to read.
=> Simplify Moller-Bhabha test harness

app/CMakeLists.txt, app/demo-interactor/KNDemoIO.hh, app/demo-loop/GeoMaterialInterface.hh, app/demo-loop/GeoMaterialParams.cc, app/demo-loop/GeoMaterialParams.hh, app/demo-loop/GeoMaterialView.hh, app/demo-loop/LDemoIO.cc, app/demo-loop/LDemoIO.hh, app/demo-loop/LDemoInterface.hh, app/demo-loop/LDemoKernel.cu, app/demo-loop/LDemoKernel.hh, app/demo-loop/LDemoParams.cc, app/demo-loop/LDemoParams.hh, app/demo-loop/LDemoRun.cc, app/demo-loop/LDemoRun.hh, app/demo-loop/demo-loop.cc, src/base/CollectionBuilder.hh
This is partly a "request for comment" and partly a framework for filling out the to-do list on #54 for splitting up tasks. I think adding an untested but building "app" to the main repo so we can distribute the pieces should be OK... we can iterate on the pieces through merge requests, track the overall status with issue #54, and then as components mature (or get complex enough to have subtle bugs) move them into the  main `src/` directory and add tests.
=> Add skeleton for stepping loop demo

README.md
I noticed two issues in the README, which are fixed in this PR
=> Two fixes in README.md

.jenkins, CMakeLists.txt, scripts/docker/build.sh, src/geometry/GeoParams.cc, src/geometry/detail/VGNavCollection.cc, src/geometry/detail/VGNavCollection.hh
Requires: https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/803
=> Use VecGeom's new NavStatePoolView to access the NavStatePool content on device

README.md
I've gone through our CMake dependencies and updated the documentation in the README. I've also updated the contribution guidelines to reference the GitHub copyright info, since (in an unrelated project) I was recently asked to sign a dumb retroactive CLA (which ORNL legal rejected).
=> Update dependencies and copyright info

src/base/Assert.hh, test/base/Collection.test.cu
Previous value `DebugErrorType::assertion` was undefined.
=> Fix to enum value

src/CMakeLists.txt, src/physics/em/RayleighProcess.cc, src/physics/em/RayleighProcess.hh, test/physics/em/ImportedProcesses.test.cc
Add Rayleigh process and an associated test in ImportedProcesses.test.
=> Add Rayleigh process

app/CMakeLists.txt
I could not build the full physics demo in my area, because I don't enable Geant4.  
So I have added a Geant4=ON requirement for this demo app.
=> Geant4 is required to build the full physics demo app

src/physics/em/detail/MollerBhabhaInteractor.i.hh, src/physics/em/detail/MollerEnergyDistribution.i.hh, test/physics/em/MollerBhabha.test.cc
I think there's a small error in the energy cutoff in the Moller-Bhabha interactor -- @stognini could you confirm that these changes look right?
=> Moller-Bhabha fix

README.md
`CELERITAS_USE_VECGEOM` -> `CELERITAS_USE_VecGeom`
=> Update VecGeom build option in README.md

src/field/FieldDriver.hh, src/field/FieldDriver.i.hh, src/field/FieldPropagator.hh, src/field/FieldPropagator.i.hh, src/field/MagFieldTraits.hh, src/field/RungeKuttaStepper.hh, src/field/RungeKuttaStepper.i.hh, test/field/FieldDriver.test.cc, test/field/FieldDriver.test.cu, test/field/FieldPropagator.test.cc, test/field/FieldPropagator.test.cu, test/field/RungeKutta.test.cc, test/field/RungeKutta.test.cu, test/field/detail/MagTestTraits.hh
1) Added MagFieldTraits
2) Reduced template parameters for magnetic field classes
3) Followed up changes for tests codes
=> MagField Traits

src/base/Assert.hh
I realized while profiling #312 that the Celeritas assertion macros (which use CUDA `assert` under the hood) were being completely elided when building `-DCELERITAS_DEBUG=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo` because the build type adds `NDEBUG` to the CUDA flags, which disables `assert`. This PR changes the macros so that the assertion condition is still checked when asking for `DEBUG` mode, although of course we won't get a clean error message.
cc @sphamil @tmdelellis for Shift
=> Define CUDA assertion that still fails when NDEBUG

app/demo-loop/LDemoIO.cc, app/demo-loop/LDemoIO.hh, app/demo-loop/Transporter.cc, app/demo-loop/Transporter.hh, app/demo-loop/Transporter.json.hh, app/demo-loop/demo-loop.cc, app/demo-loop/diagnostic/Diagnostic.hh, app/demo-loop/diagnostic/EnergyDiagnostic.hh, app/demo-loop/diagnostic/EnergyDiagnostic.i.hh, app/demo-loop/diagnostic/ParticleProcessDiagnostic.hh, app/demo-loop/diagnostic/ParticleProcessDiagnostic.i.hh, app/demo-loop/diagnostic/StepDiagnostic.hh, app/demo-loop/diagnostic/StepDiagnostic.i.hh, app/demo-loop/diagnostic/TrackDiagnostic.hh, app/demo-loop/simple-driver.py
- Get the total simulation time, time per step, and finer-grained timing within a step
- Create a vector of diagnostics and add an option to disable them
=> Add timers to demo loop

app/demo-rasterizer/RDemoKernel.cu, app/demo-rasterizer/demo-rasterizer.cc
Reinitialize at the end of a pixel if too many surface crossings are encountered in a single pixel. This bounds the total number of inner loops and prevents particles from being stuck in vecgeom. Without this change, the [CMS raytrace](https://github.com/celeritas-project/benchmarks/blob/master/cms-raytrace/raytrace.ipynb) hangs indefinitely.
=> Fix rasterizer

app/demo-loop/Transporter.cc, app/demo-loop/Transporter.hh, app/demo-loop/Transporter.json.hh
Store the number of track initializers at each step in the demo loop result.
=> Store number of track initializers in demo loop

app/demo-loop/diagnostic/StepDiagnostic.hh, src/celeritas/em/distribution/UrbanMscHelper.hh, src/celeritas/em/launcher/LivermorePELauncher.hh
=> Fix step diagnostic, element resampling for Livermore PE

app/geo-check/GCheckKernel.cu
This corrects a change that I missed on PR #446, to avoid double transferring an array from device to host.
=> Avoid double transfer from device (see PR #446)

src/celeritas/phys/PDGNumber.hh, src/celeritas/phys/Primary.hh, src/celeritas/phys/PrimaryGenerator.cc, src/celeritas/phys/PrimaryGenerator.hh, src/celeritas/phys/PrimaryGeneratorOptionsIO.json.cc, test/CMakeLists.txt, test/celeritas/phys/PrimaryGenerator.test.cc
Fixes errors reported by @hahnjo in  https://github.com/celeritas-project/celeritas/pull/463#discussion_r936782490 .
=> Fix uninitialized data access in primary generator

src/celeritas/ext/GeantImporter.cc, src/celeritas/ext/GeantImporter.hh, src/celeritas/ext/detail/ImportProcessConverter.cc, src/celeritas/io/ImportData.hh, test/CMakeLists.txt, test/celeritas/ext/GeantImporter.test.cc, test/celeritas/ext/RootImporter.test.cc
This should allow us to integrate celeritas into a Geant4 application running full physics while exporting a limited subset of the data.
=> Filter imported data from Geant4 based on user options

app/demo-loop/LDemoIO.cc, src/CMakeLists.txt, src/celeritas/phys/ProcessBuilder.cc, src/celeritas/phys/ProcessBuilder.hh
The loop demo app now loads processes based on what's in the ROOT file (or what's in the GeantImporter-loaded data).
=> Build processes based on exported data

src/celeritas/ext/detail/BVHNavigator.hh
All updates from AdePT developers since past October are part of this update.
All tests pass locally.
=> Bring latest upstream updates to the BVHNavigator

app/CMakeLists.txt, src/celeritas/phys/PhysicsParamsOutput.cc, test/CMakeLists.txt, test/celeritas/phys/PrimaryGenerator.test.cc
- Missing link target from tests that include JsonPimpl
- Link to exporter when json unavailable
- Unguarded json includes
=> Fix JSON build issues

src/celeritas/user/StepCollector.cc, src/celeritas/user/StepCollector.hh, src/celeritas/user/StepData.hh, src/celeritas/user/StepInterface.hh, src/celeritas/user/detail/StepGatherAction.cc, src/celeritas/user/detail/StepGatherAction.hh, src/celeritas/user/detail/StepGatherLauncher.hh, test/celeritas/user/ExampleStepCallback.cc, test/celeritas/user/ExampleStepCallback.hh, test/celeritas/user/StepCollectorTestBase.cc
This moves the "selection" into the `StepInterface` where it's more appropriate. I could also extend this branch to reimplement one or two of the "diagnostic" classes as a step interface.
=> Add finer granularity to step collector

CMakeLists.txt, README.md, doc/appendices/development.rst, doc/infrastructure.rst, interface/CMakeLists.txt, scripts/README.md, scripts/cmake-presets/goldfinger.json, scripts/dev/iwyu-apple-clang.imp, scripts/dev/run-iwyu.sh, scripts/spack.yaml, src/corecel/Types.hh
This fixes a few issues with a recent rebuild on my mac:
- MacOS 13
- SWIG 4.1
And it refactors and updates the build documentation to fix #570 .
=> Fix build documentation and issues with newer toolchains

app/CMakeLists.txt, app/demo-geant-integration/ActionInitialization.cc, app/demo-geant-integration/GlobalSetup.cc, app/demo-geant-integration/MasterRunAction.cc, app/demo-geant-integration/MasterRunAction.hh, app/demo-geant-integration/simple-cms-test.mac.in, src/accel/CMakeLists.txt, src/accel/SetupOptions.hh, src/accel/SharedParams.cc, src/accel/SharedParams.hh
This simply writes out diagnostics (kernel diagnostics being the most important) at the end of the run.
=> Add diagnostic output to geant demo

.git-blame-ignore-revs, doc/CMakeLists.txt, doc/appendices/administration.rst, doc/appendices/release-history.rst, scripts/cmake-presets/summit.json, src/accel/detail/HitProcessor.cc
Fix a few tiny build errors on Summit, add "git blame ignore" entries for the recent IWYU and clang-format, and update the release notes with recent changes.
=> Release v0.2.0

src/celeritas/ext/VecgeomParams.cc
This (partially?) addresses https://github.com/celeritas-project/celeritas/issues/614
=> VecGeom/Cuda: set the stack limit to 16K when CELERITAS_DEBUG=ON

src/accel/detail/HitManager.cc
=> Fix hit mapping when using GDML geometry with pointers
